import numpy as np
import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
from astropy.io import fits 
from scipy import stats
import random
import mycode2
np.set_printoptions(threshold='nan')

#plt.rc('grid',alpha=0.7) # modify rcparams
#plt.rc('grid',color='white')
#plt.rc('grid',linestyle='-')
plt.rc('legend',frameon='False')
plt.rc('xtick.major',size=2)
plt.rc('ytick.major',size=2)
plt.rc('axes',axisbelow='True')
plt.rc('axes',grid='False')
plt.rc('axes',facecolor='white')
plt.rc('axes',linewidth=0.5)
plt.rc('xtick.major',width=0.5)
plt.rc('ytick.major',width=0.5)
plt.rc('xtick',direction='in')
plt.rc('ytick',direction='in')
plt.rc('xtick',labelsize='5')
plt.rc('ytick',labelsize='5')
plt.rc('text',usetex='True')
plt.rc('font',family='serif')
plt.rc('font',style='normal')
plt.rc('font',serif='Century')
plt.rc('savefig',format='eps')
plt.rc('lines',markeredgewidth=0)
plt.rc('lines',markersize=2)
            
tuc2_data1='tuc2teffprior_mixturepost_equal_weights.dat'
gru1_data1='gru1teffprior_mixturepost_equal_weights.dat'

out1='tuc2gru1teffprior_mixturecommands.tex'
out2='tuc2gru1teffprior_mixture_table.tex'
g1=open(out1,'w')
g2=open(out2,'w')

with open(tuc2_data1) as f: # read data file
    data=f.readlines()

tuc2_vmean=[]
tuc2_vdisp=[]
tuc2_vgrad=[]
tuc2_vtheta=[]
tuc2_fehmean=[]
tuc2_fehdisp=[]
tuc2_fehgrad=[]
tuc2_vmean2=[]
tuc2_vdisp2=[]
tuc2_fehmean2=[]
tuc2_fehdisp2=[]
tuc2_fmem=[]
tuc2_like=[]

for line in data: # fill arrays
    p=line.split()
    tuc2_fmem.append(float(p[0]))
    tuc2_vmean.append(float(p[1]))
    tuc2_vdisp.append(float(p[2]))
    tuc2_fehmean.append(float(p[3]))
    tuc2_fehdisp.append(float(p[4]))
    tuc2_vmean2.append(float(p[5]))
    tuc2_vdisp2.append(float(p[6]))
    tuc2_fehmean2.append(float(p[7]))
    tuc2_fehdisp2.append(float(p[8]))
    tuc2_vgrad.append(float(p[9]))
    tuc2_vtheta.append(float(p[10]))
    tuc2_fehgrad.append(float(p[11]))
    tuc2_like.append(float(p[12]))

tuc2_fmem=np.array(tuc2_fmem)
tuc2_vmean=np.array(tuc2_vmean)
tuc2_vdisp=np.array(tuc2_vdisp)
tuc2_fehmean=np.array(tuc2_fehmean)
tuc2_fehdisp=np.array(tuc2_fehdisp)
tuc2_vmean2=np.array(tuc2_vmean2)
tuc2_vdisp2=np.array(tuc2_vdisp2)
tuc2_fehmean2=np.array(tuc2_fehmean2)
tuc2_fehdisp2=np.array(tuc2_fehdisp2)
tuc2_vgrad=np.array(tuc2_vgrad)
tuc2_vtheta=np.array(tuc2_vtheta)
tuc2_fehgrad=np.array(tuc2_fehgrad)
tuc2_like=np.array(tuc2_like)

with open(gru1_data1) as f: # read data file
    data=f.readlines()

gru1_vmean=[]
gru1_vdisp=[]
gru1_vgrad=[]
gru1_vtheta=[]
gru1_fehmean=[]
gru1_fehdisp=[]
gru1_fehgrad=[]
gru1_vmean2=[]
gru1_vdisp2=[]
gru1_fehmean2=[]
gru1_fehdisp2=[]
gru1_fmem=[]
gru1_like=[]

for line in data: # fill arrays
    p=line.split()
    gru1_fmem.append(float(p[0]))
    gru1_vmean.append(float(p[1]))
    gru1_vdisp.append(float(p[2]))
    gru1_fehmean.append(float(p[3]))
    gru1_fehdisp.append(float(p[4]))
    gru1_vmean2.append(float(p[5]))
    gru1_vdisp2.append(float(p[6]))
    gru1_fehmean2.append(float(p[7]))
    gru1_fehdisp2.append(float(p[8]))
    gru1_vgrad.append(float(p[9]))
    gru1_vtheta.append(float(p[10]))
    gru1_fehgrad.append(float(p[11]))
    gru1_like.append(float(p[12]))

gru1_fmem=np.array(gru1_fmem)
gru1_vmean=np.array(gru1_vmean)
gru1_vdisp=np.array(gru1_vdisp)
gru1_fehmean=np.array(gru1_fehmean)
gru1_fehdisp=np.array(gru1_fehdisp)
gru1_vmean2=np.array(gru1_vmean2)
gru1_vdisp2=np.array(gru1_vdisp2)
gru1_fehmean2=np.array(gru1_fehmean2)
gru1_fehdisp2=np.array(gru1_fehdisp2)
gru1_vgrad=np.array(gru1_vgrad)
gru1_vtheta=np.array(gru1_vtheta)
gru1_fehgrad=np.array(gru1_fehgrad)
gru1_like=np.array(gru1_like)


gs=plt.GridSpec(7,7) # define multi-panel plot
gs.update(wspace=0,hspace=0) # specify inter-panel spacing
fig=plt.figure(figsize=(6,6)) # define plot size
#fig.set_

tuc2_statsfmem=np.percentile(tuc2_fmem,[2.5,16.,50.,84.,97.5])
tuc2_statsvmean=np.percentile(tuc2_vmean,[2.5,16.,50.,84.,97.5])
tuc2_statsvdisp=np.percentile(tuc2_vdisp,[2.5,16.,50.,84.,97.5])
tuc2_statsfehmean=np.percentile(tuc2_fehmean,[2.5,16.,50.,84.,97.5])
tuc2_statsfehdisp=np.percentile(tuc2_fehdisp,[2.5,16.,50.,84.,97.5])
tuc2_statsvmean2=np.percentile(tuc2_vmean2,[2.5,16.,50.,84.,97.5])
tuc2_statsvdisp2=np.percentile(tuc2_vdisp2,[2.5,16.,50.,84.,97.5])
tuc2_statsfehmean2=np.percentile(tuc2_fehmean2,[2.5,16.,50.,84.,97.5])
tuc2_statsfehdisp2=np.percentile(tuc2_fehdisp2,[2.5,16.,50.,84.,97.5])
tuc2_statsvgrad=np.percentile(tuc2_vgrad,[2.5,16.,50.,84.,97.5])
tuc2_statsvtheta=np.percentile(tuc2_vtheta,[2.5,16.,50.,84.,97.5])
tuc2_statsfehgrad=np.percentile(tuc2_fehgrad,[2.5,16.,50.,84.,97.5])

gru1_statsfmem=np.percentile(gru1_fmem,[2.5,16.,50.,84.,97.5])
gru1_statsvmean=np.percentile(gru1_vmean,[2.5,16.,50.,84.,97.5])
gru1_statsvdisp=np.percentile(gru1_vdisp,[2.5,16.,50.,84.,97.5])
gru1_statsfehmean=np.percentile(gru1_fehmean,[2.5,16.,50.,84.,97.5])
gru1_statsfehdisp=np.percentile(gru1_fehdisp,[2.5,16.,50.,84.,97.5])
gru1_statsvmean2=np.percentile(gru1_vmean2,[2.5,16.,50.,84.,97.5])
gru1_statsvdisp2=np.percentile(gru1_vdisp2,[2.5,16.,50.,84.,97.5])
gru1_statsfehmean2=np.percentile(gru1_fehmean2,[2.5,16.,50.,84.,97.5])
gru1_statsfehdisp2=np.percentile(gru1_fehdisp2,[2.5,16.,50.,84.,97.5])
gru1_statsvgrad=np.percentile(gru1_vgrad,[2.5,16.,50.,84.,97.5])
gru1_statsvtheta=np.percentile(gru1_vtheta,[2.5,16.,50.,84.,97.5])
gru1_statsfehgrad=np.percentile(gru1_fehgrad,[2.5,16.,50.,84.,97.5])

ax6_0=fig.add_subplot(gs[6,0])
ax5_0=fig.add_subplot(gs[5,0])
ax4_0=fig.add_subplot(gs[4,0])
ax3_0=fig.add_subplot(gs[3,0])
ax2_0=fig.add_subplot(gs[2,0])
ax1_0=fig.add_subplot(gs[1,0])

ax5_1=fig.add_subplot(gs[5,1])
ax4_1=fig.add_subplot(gs[4,1])
ax3_1=fig.add_subplot(gs[3,1])
ax2_1=fig.add_subplot(gs[2,1])
ax1_1=fig.add_subplot(gs[1,1])

ax4_2=fig.add_subplot(gs[4,2])
ax3_2=fig.add_subplot(gs[3,2])
ax2_2=fig.add_subplot(gs[2,2])
ax1_2=fig.add_subplot(gs[1,2])

ax3_3=fig.add_subplot(gs[3,3])
ax2_3=fig.add_subplot(gs[2,3])
ax1_3=fig.add_subplot(gs[1,3])

ax2_4=fig.add_subplot(gs[2,4])
ax1_4=fig.add_subplot(gs[1,4])

ax1_5=fig.add_subplot(gs[1,5])



#ax1_4=fig.add_subplot(gs[1,4])

ax1_6=fig.add_subplot(gs[1,6])
ax0_5=fig.add_subplot(gs[0,5])
ax0_4=fig.add_subplot(gs[0,4])
ax0_3=fig.add_subplot(gs[0,3])
ax0_2=fig.add_subplot(gs[0,2])
ax0_1=fig.add_subplot(gs[0,1])
ax0_0=fig.add_subplot(gs[0,0])

#    ax0_12=fig.add_subplot(gs[0,12])
vmeanlim=[-155,-110]
vdisplim=[0,12]
vgradlim=[0,4.5]
vthetalim=[-179,179]
fehmeanlim=[-4.99,0.99] 
fehdisplim=[0.01,2]
fehgradlim=[-0.99,0.99]  

vmeanticks=[-150,-140,-130,-120,-110]
vdispticks=[2,4,6,8,10]
vgradticks=[2,4,6,8,10]
vthetaticks=[-150,0,150]
fehmeanticks=[-4,-3,-2,-1,0]
fehdispticks=[0.5,1,1.5]
fehgradticks=[-0.5,0,0.5]

vmeanlabel=[r'$\langle v_{\rm los}\rangle$ [km/s]']
vdisplabel=[r'$\sigma_v$ [km/s]']
vgradlabel=[r'$k_{v_{\rm los}}$ $\bigl[ \frac{\rm km/s}{\prime}\bigr ]$']
vthetalabel=[r'$\theta_{v_{\rm los}}$ $[^{\circ}]$']
fehmeanlabel=[r'$\langle [\mathrm{Fe/H}]\rangle $ [dex]']
fehdisplabel=[r'$\sigma_{[\mathrm{Fe/H}]}$ [dex]']
fehgradlabel=[r'$k_{[\mathrm{Fe/H}]} $ $\bigl [ \frac{\rm dex}{\prime}\bigr ]$']

ax6_0.set_xlabel(vmeanlabel[0],fontsize=7,rotation=0)
ax6_0.set_ylabel(vdisplabel[0],fontsize=7,rotation=90,labelpad=1)
ax6_0.set_xlim(vmeanlim)
ax6_0.set_ylim(vdisplim)
ax6_0.set_xscale(u'linear')
ax6_0.set_yscale(u'linear')
ax6_0.set_xticks(vmeanticks)
ax6_0.set_xticklabels(vmeanticks,rotation=0)
ax6_0.set_yticks(vdispticks)
ax6_0.set_yticklabels(vdispticks,rotation=0)
#ax6_0.scatter(vmean2,vdisp2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax6_0.scatter(gru1_vmean,gru1_vdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax6_0.scatter(tuc2_vmean,tuc2_vdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax6_0.set_xlabel(vmeanlabel[0],fontsize=7,rotation=0)
ax5_0.set_ylabel(vgradlabel[0],fontsize=7,rotation=90,labelpad=15)
ax5_0.set_xlim(vmeanlim)
ax5_0.set_ylim(vgradlim)
ax5_0.set_xscale(u'linear')
ax5_0.set_yscale(u'linear')
ax5_0.set_xticks(vmeanticks)
#ax6_0.set_xticklabels(vmeanticks,rotation=0)
ax5_0.set_yticks(vgradticks)
ax5_0.set_yticklabels(vgradticks,rotation=0)
ax5_0.xaxis.set_major_formatter(plt.NullFormatter())
#ax5_0.scatter(vmean2,vgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax5_0.scatter(gru1_vmean,gru1_vgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax5_0.scatter(tuc2_vmean,tuc2_vgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax5_0.set_xlabel(vmeanlabel[0],fontsize=7,rotation=0)
ax4_0.set_ylabel(vthetalabel[0],fontsize=7,rotation=90,labelpad=1)
ax4_0.set_xlim(vmeanlim)
ax4_0.set_ylim(vthetalim)
ax4_0.set_xscale(u'linear')
ax4_0.set_yscale(u'linear')
ax5_0.set_xticks(vmeanticks)
#ax5_0.set_xticklabels(vmeanticks,rotation=0)
ax4_0.set_yticks(vthetaticks)
ax4_0.set_yticklabels(vthetaticks,rotation=0)
ax4_0.xaxis.set_major_formatter(plt.NullFormatter())
#ax4_0.scatter(vmean2,vtheta2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax4_0.scatter(gru1_vmean,gru1_vtheta,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax4_0.scatter(tuc2_vmean,tuc2_vtheta,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax4_0.set_xlabel(vmeanlabel[0],fontsize=7,rotation=0)
ax3_0.set_ylabel(fehmeanlabel[0],fontsize=7,rotation=90,labelpad=15)
ax3_0.set_xlim(vmeanlim)
ax3_0.set_ylim(fehmeanlim)
ax3_0.set_xscale(u'linear')
ax3_0.set_yscale(u'linear')
ax3_0.set_xticks(vmeanticks)
#ax4_0.set_xticklabels(vmeanticks,rotation=0)
ax3_0.set_yticks(fehmeanticks)
ax3_0.set_yticklabels(fehmeanticks,rotation=0)
ax3_0.xaxis.set_major_formatter(plt.NullFormatter())
#ax3_0.scatter(vmean2,fehmean2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax3_0.scatter(gru1_vmean,gru1_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax3_0.scatter(tuc2_vmean,tuc2_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax3_0.set_xlabel(vmeanlabel[0],fontsize=7,rotation=0)
ax2_0.set_ylabel(fehdisplabel[0],fontsize=7,rotation=90,labelpad=1)
ax2_0.set_xlim(vmeanlim)
ax2_0.set_ylim(fehdisplim)
ax2_0.set_xscale(u'linear')
ax2_0.set_yscale(u'linear')
ax2_0.set_xticks(vmeanticks)
#ax3_0.set_xticklabels(vmeanticks,rotation=0)
ax2_0.set_yticks(fehdispticks)
ax2_0.set_yticklabels(fehdispticks,rotation=0)
ax2_0.xaxis.set_major_formatter(plt.NullFormatter())
#ax2_0.scatter(vmean2,fehdisp2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax2_0.scatter(gru1_vmean,gru1_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax2_0.scatter(tuc2_vmean,tuc2_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax2_0.set_xlabel(vmeanlabel[0],fontsize=7,rotation=0)
ax1_0.set_ylabel(fehgradlabel[0],fontsize=7,rotation=90,labelpad=15)
ax1_0.set_xlim(vmeanlim)
ax1_0.set_ylim(fehgradlim)
ax1_0.set_xscale(u'linear')
ax1_0.set_yscale(u'linear')
ax1_0.set_xticks(vmeanticks)
#ax2_0.set_xticklabels(vmeanticks,rotation=0)
ax1_0.set_yticks(fehgradticks)
ax1_0.set_yticklabels(fehgradticks,rotation=0)
ax1_0.xaxis.set_major_formatter(plt.NullFormatter())
#ax1_0.scatter(vmean2,fehgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax1_0.scatter(gru1_vmean,gru1_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax1_0.scatter(tuc2_vmean,tuc2_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

ax0_0.set_ylabel('probability',fontsize=7,rotation=90,labelpad=1)
ax0_0.xaxis.set_major_formatter(plt.NullFormatter())
ax0_0.set_xticks(vmeanticks)
ax0_0.yaxis.set_major_formatter(plt.NullFormatter())
#ax0_0.hist(vmean2,bins=50,range=vmeanlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_0.hist(tuc2_vmean,bins=50,range=vmeanlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.5,label='Tuc 2')
ax0_0.hist(gru1_vmean,bins=50,range=vmeanlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5,label='Gru 1')
ax0_0.legend(loc=2,fontsize=7,handlelength=0.5,numpoints=1,scatterpoints=1,shadow=False)



ax5_1.set_xlabel(vdisplabel[0],fontsize=7,rotation=0)
#ax5_1.set_ylabel(vgradlabel[0],fontsize=7,rotation=90,labelpad=5)
ax5_1.set_xlim(vdisplim)
ax5_1.set_ylim(vgradlim)
ax5_1.set_xscale(u'linear')
ax5_1.set_yscale(u'linear')
ax5_1.set_xticks(vdispticks)
ax5_1.set_xticklabels(vdispticks,rotation=0)
ax5_1.set_yticks(vgradticks)
ax5_1.set_yticklabels(vgradticks,rotation=0)
ax5_1.yaxis.set_major_formatter(plt.NullFormatter())
#ax5_1.scatter(vdisp2,vgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax5_1.scatter(gru1_vdisp,gru1_vgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax5_1.scatter(tuc2_vdisp,tuc2_vgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax5_1.set_xlabel(vdisplabel[0],fontsize=7,rotation=0)
#ax4_1.set_ylabel(vthetalabel[0],fontsize=7,rotation=90,labelpad=5)
ax4_1.set_xlim(vdisplim)
ax4_1.set_ylim(vthetalim)
ax4_1.set_xscale(u'linear')
ax4_1.set_yscale(u'linear')
ax4_1.set_xticks(vdispticks)
#ax4_1.set_xticklabels(vdispticks,rotation=0)
ax4_1.set_yticks(vthetaticks)
#ax4_1.set_yticklabels(vthetaticks,rotation=0)
ax4_1.xaxis.set_major_formatter(plt.NullFormatter())
ax4_1.yaxis.set_major_formatter(plt.NullFormatter())
#ax4_1.scatter(vdisp2,vtheta2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax4_1.scatter(gru1_vdisp,gru1_vtheta,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax4_1.scatter(tuc2_vdisp,tuc2_vtheta,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax3_1.set_xlabel(vdisplabel[0],fontsize=7,rotation=0)
#ax3_1.set_ylabel(fehmeanlabel[0],fontsize=7,rotation=90,labelpad=5)
ax3_1.set_xlim(vdisplim)
ax3_1.set_ylim(fehmeanlim)
ax3_1.set_xscale(u'linear')
ax3_1.set_yscale(u'linear')
ax3_1.set_xticks(vdispticks)
#ax3_1.set_xticklabels(vdispticks,rotation=0)
ax3_1.set_yticks(fehmeanticks)
#ax3_1.set_yticklabels(fehmeanticks,rotation=0)
ax3_1.yaxis.set_major_formatter(plt.NullFormatter())
ax3_1.xaxis.set_major_formatter(plt.NullFormatter())
#ax3_1.scatter(vdisp2,fehmean2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax3_1.scatter(gru1_vdisp,gru1_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax3_1.scatter(tuc2_vdisp,tuc2_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax2_1.set_xlabel(vdisplabel[0],fontsize=7,rotation=0)
#ax2_1.set_ylabel(fehdisplabel[0],fontsize=7,rotation=90,labelpad=5)
ax2_1.set_xlim(vdisplim)
ax2_1.set_ylim(fehdisplim)
ax2_1.set_xscale(u'linear')
ax2_1.set_yscale(u'linear')
ax2_1.set_xticks(vdispticks)
#ax2_1.set_xticklabels(vdispticks,rotation=0)
ax2_1.set_yticks(fehdispticks)
#ax2_1.set_yticklabels(fehdispticks,rotation=0)
ax2_1.yaxis.set_major_formatter(plt.NullFormatter())
ax2_1.xaxis.set_major_formatter(plt.NullFormatter())
#ax2_1.scatter(vdisp2,fehdisp2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax2_1.scatter(gru1_vdisp,gru1_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax2_1.scatter(tuc2_vdisp,tuc2_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax1_1.set_xlabel(vdisplabel[0],fontsize=7,rotation=0)
#ax1_1.set_ylabel(fehgradlabel[0],fontsize=7,rotation=90,labelpad=5)
ax1_1.set_xlim(vdisplim)
ax1_1.set_ylim(fehgradlim)
ax1_1.set_xscale(u'linear')
ax1_1.set_yscale(u'linear')
ax1_1.set_xticks(vdispticks)
#ax1_1.set_xticklabels(vdispticks,rotation=0)
ax1_1.set_yticks(fehgradticks)
#ax1_1.set_yticklabels(fehgradticks,rotation=0)
ax1_1.yaxis.set_major_formatter(plt.NullFormatter())
ax1_1.xaxis.set_major_formatter(plt.NullFormatter())
#ax1_1.scatter(vdisp2,fehgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax1_1.scatter(gru1_vdisp,gru1_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax1_1.scatter(tuc2_vdisp,tuc2_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax0_1.set_ylabel('probability',fontsize=7,rotation=90,labelpad=5)
ax0_1.xaxis.set_major_formatter(plt.NullFormatter())
ax0_1.set_xticks(vdispticks)
ax0_1.yaxis.set_major_formatter(plt.NullFormatter())
#ax0_1.hist(vdisp2,bins=50,range=vdisplim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_1.hist(gru1_vdisp,bins=50,range=vdisplim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_1.hist(tuc2_vdisp,bins=50,range=vdisplim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.5)



ax4_2.set_xlabel(vgradlabel[0],fontsize=7,rotation=0)
#ax4_2.set_ylabel(vthetalabel[0],fontsize=7,rotation=90,labelpad=5)
ax4_2.set_xlim(vgradlim)
ax4_2.set_ylim(vthetalim)
ax4_2.set_xscale(u'linear')
ax4_2.set_yscale(u'linear')
ax4_2.set_xticks(vgradticks)
#ax4_2.set_xticklabels(vgradticks,rotation=0)
ax4_2.set_yticks(vthetaticks)
#ax4_2.set_yticklabels(vthetaticks,rotation=0)
ax4_2.yaxis.set_major_formatter(plt.NullFormatter())
#ax4_2.scatter(vgrad2,vtheta2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax4_2.scatter(gru1_vgrad,gru1_vtheta,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax4_2.scatter(tuc2_vgrad,tuc2_vtheta,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax3_2.set_xlabel(vgradlabel[0],fontsize=7,rotation=0)
#ax3_2.set_ylabel(fehmeanlabel[0],fontsize=7,rotation=90,labelpad=5)
ax3_2.set_xlim(vgradlim)
ax3_2.set_ylim(fehmeanlim)
ax3_2.set_xscale(u'linear')
ax3_2.set_yscale(u'linear')
ax3_2.set_xticks(vgradticks)
#ax3_2.set_xticklabels(vgradticks,rotation=0)
ax3_2.set_yticks(fehmeanticks)
#ax3_2.set_yticklabels(fehmeanticks,rotation=0)
ax3_2.yaxis.set_major_formatter(plt.NullFormatter())
ax3_2.xaxis.set_major_formatter(plt.NullFormatter())
#ax3_2.scatter(vgrad2,fehmean2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax3_2.scatter(gru1_vgrad,gru1_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax3_2.scatter(tuc2_vgrad,tuc2_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax2_2.set_xlabel(vgradlabel[0],fontsize=7,rotation=0)
#ax2_2.set_ylabel(fehdisplabel[0],fontsize=7,rotation=90,labelpad=5)
ax2_2.set_xlim(vgradlim)
ax2_2.set_ylim(fehdisplim)
ax2_2.set_xscale(u'linear')
ax2_2.set_yscale(u'linear')
ax2_2.set_xticks(vgradticks)
#ax2_2.set_xticklabels(vgradticks,rotation=0)
ax2_2.set_yticks(fehdispticks)
#ax2_2.set_yticklabels(fehdispticks,rotation=0)
ax2_2.yaxis.set_major_formatter(plt.NullFormatter())
ax2_2.xaxis.set_major_formatter(plt.NullFormatter())
#ax2_2.scatter(vgrad2,fehdisp2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax2_2.scatter(gru1_vgrad,gru1_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax2_2.scatter(tuc2_vgrad,tuc2_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax1_2.set_xlabel(vgradlabel[0],fontsize=7,rotation=0)
#ax1_2.set_ylabel(fehgradlabel[0],fontsize=7,rotation=90,labelpad=5)
ax1_2.set_xlim(vgradlim)
ax1_2.set_ylim(fehgradlim)
ax1_2.set_xscale(u'linear')
ax1_2.set_yscale(u'linear')
ax1_2.set_xticks(vgradticks)
#ax1_2.set_xticklabels(vgradticks,rotation=0)
ax1_2.set_yticks(fehgradticks)
#ax1_2.set_yticklabels(fehgradticks,rotation=0)
ax1_2.yaxis.set_major_formatter(plt.NullFormatter())
ax1_2.xaxis.set_major_formatter(plt.NullFormatter())
#ax1_2.scatter(vgrad2,fehgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax1_2.scatter(gru1_vgrad,gru1_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax1_2.scatter(tuc2_vgrad,tuc2_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax0_2.set_ylabel('probability',fontsize=7,rotation=90,labelpad=5)
ax0_2.xaxis.set_major_formatter(plt.NullFormatter())
ax0_2.set_xticks(vgradticks)
ax0_2.yaxis.set_major_formatter(plt.NullFormatter())
#ax0_2.hist(vgrad2,bins=50,range=vgradlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_2.hist(gru1_vgrad,bins=50,range=vgradlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_2.hist(tuc2_vgrad,bins=50,range=vgradlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.5)

ax3_3.set_xlabel(vthetalabel[0],fontsize=7,rotation=0)
#ax3_3.set_ylabel(fehmeanlabel[0],fontsize=7,rotation=90,labelpad=5)
ax3_3.set_xlim(vthetalim)
ax3_3.set_ylim(fehmeanlim)
ax3_3.set_xscale(u'linear')
ax3_3.set_yscale(u'linear')
ax3_3.set_xticks(vthetaticks)
#ax3_3.set_xticklabels(vthetaticks,rotation=0)
ax3_3.set_yticks(fehmeanticks)
#ax3_3.set_yticklabels(fehmeanticks,rotation=0)
ax3_3.yaxis.set_major_formatter(plt.NullFormatter())
#ax3_3.scatter(vtheta2,fehmean2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax3_3.scatter(gru1_vtheta,gru1_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax3_3.scatter(tuc2_vtheta,tuc2_fehmean,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax2_3.set_xlabel(vthetalabel[0],fontsize=7,rotation=0)
#ax2_3.set_ylabel(fehdisplabel[0],fontsize=7,rotation=90,labelpad=5)
ax2_3.set_xlim(vthetalim)
ax2_3.set_ylim(fehdisplim)
ax2_3.set_xscale(u'linear')
ax2_3.set_yscale(u'linear')
ax2_3.set_xticks(vthetaticks)
#ax2_3.set_xticklabels(vthetaticks,rotation=0)
ax2_3.set_yticks(fehdispticks)
#ax2_3.set_yticklabels(fehdispticks,rotation=0)
ax2_3.yaxis.set_major_formatter(plt.NullFormatter())
ax2_3.xaxis.set_major_formatter(plt.NullFormatter())
#ax2_3.scatter(vtheta2,fehdisp2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax2_3.scatter(gru1_vtheta,gru1_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax2_3.scatter(tuc2_vtheta,tuc2_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax1_3.set_xlabel(vthetalabel[0],fontsize=7,rotation=0)
#ax1_3.set_ylabel(fehgradlabel[0],fontsize=7,rotation=90,labelpad=5)
ax1_3.set_xlim(vthetalim)
ax1_3.set_ylim(fehgradlim)
ax1_3.set_xscale(u'linear')
ax1_3.set_yscale(u'linear')
ax1_3.set_xticks(vthetaticks)
#ax1_3.set_xticklabels(vthetaticks,rotation=0)
ax1_3.set_yticks(fehgradticks)
#ax1_3.set_yticklabels(fehgradticks,rotation=0)
ax1_3.yaxis.set_major_formatter(plt.NullFormatter())
ax1_3.xaxis.set_major_formatter(plt.NullFormatter())
#ax1_3.scatter(vtheta2,fehgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax1_3.scatter(gru1_vtheta,gru1_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax1_3.scatter(tuc2_vtheta,tuc2_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax0_3.set_ylabel('probability',fontsize=7,rotation=90,labelpad=5)
ax0_3.xaxis.set_major_formatter(plt.NullFormatter())
ax0_3.set_xticks(vthetaticks)
ax0_3.yaxis.set_major_formatter(plt.NullFormatter())
#ax0_3.hist(vtheta2,bins=50,range=vthetalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_3.hist(gru1_vtheta,bins=50,range=vthetalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_3.hist(tuc2_vtheta,bins=50,range=vthetalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.5)


ax2_4.set_xlabel(fehmeanlabel[0],fontsize=7,rotation=0)
#ax2_4.set_ylabel(fehdisplabel[0],fontsize=7,rotation=90,labelpad=5)
ax2_4.set_xlim(fehmeanlim)
ax2_4.set_ylim(fehdisplim)
ax2_4.set_xscale(u'linear')
ax2_4.set_yscale(u'linear')
ax2_4.set_xticks(fehmeanticks)
#ax2_4.set_xticklabels(fehmeanticks,rotation=0)
ax2_4.set_yticks(fehdispticks)
#ax2_4.set_yticklabels(fehdispticks,rotation=0)
ax2_4.yaxis.set_major_formatter(plt.NullFormatter())
#ax2_4.scatter(fehmean2,fehdisp2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax2_4.scatter(gru1_fehmean,gru1_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax2_4.scatter(tuc2_fehmean,tuc2_fehdisp,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax1_4.set_xlabel(fehmeanlabel[0],fontsize=7,rotation=0)
#ax1_4.set_ylabel(fehgradlabel[0],fontsize=7,rotation=90,labelpad=5)
ax1_4.set_xlim(fehmeanlim)
ax1_4.set_ylim(fehgradlim)
ax1_4.set_xscale(u'linear')
ax1_4.set_yscale(u'linear')
ax1_4.set_xticks(fehmeanticks)
#ax1_4.set_xticklabels(fehmeanticks,rotation=0)
ax1_4.set_yticks(fehgradticks)
#ax1_4.set_yticklabels(fehgradticks,rotation=0)
ax1_4.yaxis.set_major_formatter(plt.NullFormatter())
ax1_4.xaxis.set_major_formatter(plt.NullFormatter())
#ax1_4.scatter(fehmean2,fehgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax1_4.scatter(gru1_fehmean,gru1_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax1_4.scatter(tuc2_fehmean,tuc2_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax0_4.set_ylabel('probability',fontsize=7,rotation=90,labelpad=5)
ax0_4.xaxis.set_major_formatter(plt.NullFormatter())
ax0_4.set_xticks(fehmeanticks)
ax0_4.yaxis.set_major_formatter(plt.NullFormatter())
#ax0_4.hist(fehmean2,bins=50,range=fehmeanlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_4.hist(gru1_fehmean,bins=50,range=fehmeanlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_4.hist(tuc2_fehmean,bins=50,range=fehmeanlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.5)


ax1_5.set_xlabel(fehdisplabel[0],fontsize=7,rotation=0)
#ax1_5.set_ylabel(fehgradlabel[0],fontsize=7,rotation=90,labelpad=5)
ax1_5.set_xlim(fehdisplim)
ax1_5.set_ylim(fehgradlim)
ax1_5.set_xscale(u'linear')
ax1_5.set_yscale(u'linear')
ax1_5.set_xticks(fehdispticks)
#ax1_5.set_xticklabels(fehdispticks,rotation=0)
ax1_5.set_yticks(fehgradticks)
#ax1_5.set_yticklabels(fehgradticks,rotation=0)
ax1_5.yaxis.set_major_formatter(plt.NullFormatter())
#ax1_5.scatter(fehdisp2,fehgrad2,s=1,lw=0,edgecolor='none',alpha=0.75,marker='.',color='b',rasterized=True)
ax1_5.scatter(gru1_fehdisp,gru1_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='b',rasterized=True)
ax1_5.scatter(tuc2_fehdisp,tuc2_fehgrad,s=1,lw=0,edgecolor='none',alpha=0.35,marker='.',color='r',rasterized=True)

#ax0_5.set_ylabel('probability',fontsize=7,rotation=90,labelpad=5)
ax0_5.xaxis.set_major_formatter(plt.NullFormatter())
ax0_5.set_xticks(fehdispticks)
ax0_5.yaxis.set_major_formatter(plt.NullFormatter())
#ax0_5.hist(fehdisp2,bins=50,range=fehdisplim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_5.hist(gru1_fehdisp,bins=50,range=fehdisplim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='b',linewidth=0.5)
ax0_5.hist(tuc2_fehdisp,bins=50,range=fehdisplim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.5)

ax1_6.set_xlabel('probability',fontsize=7,rotation=0,labelpad=5)
ax1_6.yaxis.set_major_formatter(plt.NullFormatter())
ax1_6.xaxis.set_major_formatter(plt.NullFormatter())
ax1_6.set_yticks(fehgradticks)
#ax1_6.hist(fehgrad2,bins=50,range=fehgradlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='horizontal',color='b',linewidth=0.5)
ax1_6.hist(gru1_fehgrad,bins=50,range=fehgradlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='horizontal',color='b',linewidth=0.5)
ax1_6.hist(tuc2_fehgrad,bins=50,range=fehgradlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='horizontal',color='r',linewidth=0.5)

g1.write(r'\newcommand{\tucfmem}{$'+str(round(tuc2_statsfmem[2],2))+r'_{'+str(round(tuc2_statsfmem[1]-tuc2_statsfmem[2],2))+r'}'+r'^{+'+str(round(tuc2_statsfmem[3]-tuc2_statsfmem[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvmean}{$'+str(round(tuc2_statsvmean[2],1))+r'_{'+str(round(tuc2_statsvmean[1]-tuc2_statsvmean[2],1))+r'}'+r'^{+'+str(round(tuc2_statsvmean[3]-tuc2_statsvmean[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvdisp}{$'+str(round(tuc2_statsvdisp[2],1))+r'_{'+str(round(tuc2_statsvdisp[1]-tuc2_statsvdisp[2],1))+r'}'+r'^{+'+str(round(tuc2_statsvdisp[3]-tuc2_statsvdisp[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehmean}{$'+str(round(tuc2_statsfehmean[2],2))+r'_{'+str(round(tuc2_statsfehmean[1]-tuc2_statsfehmean[2],2))+r'}'+r'^{+'+str(round(tuc2_statsfehmean[3]-tuc2_statsfehmean[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehdisp}{$'+str(round(tuc2_statsfehdisp[2],2))+r'_{'+str(round(tuc2_statsfehdisp[1]-tuc2_statsfehdisp[2],2))+r'}'+r'^{+'+str(round(tuc2_statsfehdisp[3]-tuc2_statsfehdisp[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvmeantwo}{$'+str(round(tuc2_statsvmean2[2],1))+r'_{'+str(round(tuc2_statsvmean2[1]-tuc2_statsvmean2[2],1))+r'}'+r'^{+'+str(round(tuc2_statsvmean2[3]-tuc2_statsvmean2[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvdisptwo}{$'+str(round(tuc2_statsvdisp2[2],1))+r'_{'+str(round(tuc2_statsvdisp2[1]-tuc2_statsvdisp2[2],1))+r'}'+r'^{+'+str(round(tuc2_statsvdisp2[3]-tuc2_statsvdisp2[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehmeantwo}{$'+str(round(tuc2_statsfehmean2[2],2))+r'_{'+str(round(tuc2_statsfehmean2[1]-tuc2_statsfehmean2[2],2))+r'}'+r'^{+'+str(round(tuc2_statsfehmean2[3]-tuc2_statsfehmean2[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehdisptwo}{$'+str(round(tuc2_statsfehdisp2[2],2))+r'_{'+str(round(tuc2_statsfehdisp2[1]-tuc2_statsfehdisp2[2],2))+r'}'+r'^{+'+str(round(tuc2_statsfehdisp2[3]-tuc2_statsfehdisp2[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvgrad}{$'+str(round(tuc2_statsvgrad[2],1))+r'_{'+str(round(tuc2_statsvgrad[1]-tuc2_statsvgrad[2],1))+r'}'+r'^{+'+str(round(tuc2_statsvgrad[3]-tuc2_statsvgrad[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvtheta}{$'+str(round(tuc2_statsvtheta[2],0))+r'_{'+str(round(tuc2_statsvtheta[1]-tuc2_statsvtheta[2],0))+r'}'+r'^{+'+str(round(tuc2_statsvtheta[3]-tuc2_statsvtheta[2],0))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehgrad}{$'+str(round(tuc2_statsfehgrad[2],2))+r'_{'+str(round(tuc2_statsfehgrad[1]-tuc2_statsfehgrad[2],2))+r'}'+r'^{+'+str(round(tuc2_statsfehgrad[3]-tuc2_statsfehgrad[2],2))+r'}$'+r'}'+'\n')


g1.write(r'\newcommand{\tucfmemexpanded}{$'+str(round(tuc2_statsfmem[2],2))+r'_{'+str(round(tuc2_statsfmem[1]-tuc2_statsfmem[2],2))+r'('+str(round(tuc2_statsfmem[0]-tuc2_statsfmem[2],2))+r')}'+r'^{+'+str(round(tuc2_statsfmem[3]-tuc2_statsfmem[2],2))+r'(+'+str(round(tuc2_statsfmem[4]-tuc2_statsfmem[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvmeanexpanded}{$'+str(round(tuc2_statsvmean[2],1))+r'_{'+str(round(tuc2_statsvmean[1]-tuc2_statsvmean[2],1))+r'('+str(round(tuc2_statsvmean[0]-tuc2_statsvmean[2],1))+r')}'+r'^{+'+str(round(tuc2_statsvmean[3]-tuc2_statsvmean[2],1))+r'(+'+str(round(tuc2_statsvmean[4]-tuc2_statsvmean[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvdispexpanded}{$'+str(round(tuc2_statsvdisp[2],1))+r'_{'+str(round(tuc2_statsvdisp[1]-tuc2_statsvdisp[2],1))+r'('+str(round(tuc2_statsvdisp[0]-tuc2_statsvdisp[2],1))+r')}'+r'^{+'+str(round(tuc2_statsvdisp[3]-tuc2_statsvdisp[2],1))+r'(+'+str(round(tuc2_statsvdisp[4]-tuc2_statsvdisp[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehmeanexpanded}{$'+str(round(tuc2_statsfehmean[2],2))+r'_{'+str(round(tuc2_statsfehmean[1]-tuc2_statsfehmean[2],2))+r'('+str(round(tuc2_statsfehmean[0]-tuc2_statsfehmean[2],2))+r')}'+r'^{+'+str(round(tuc2_statsfehmean[3]-tuc2_statsfehmean[2],2))+r'(+'+str(round(tuc2_statsfehmean[4]-tuc2_statsfehmean[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehdispexpanded}{$'+str(round(tuc2_statsfehdisp[2],2))+r'_{'+str(round(tuc2_statsfehdisp[1]-tuc2_statsfehdisp[2],2))+r'('+str(round(tuc2_statsfehdisp[0]-tuc2_statsfehdisp[2],2))+r')}'+r'^{+'+str(round(tuc2_statsfehdisp[3]-tuc2_statsfehdisp[2],2))+r'(+'+str(round(tuc2_statsfehdisp[4]-tuc2_statsfehdisp[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvmeantwoexpanded}{$'+str(round(tuc2_statsvmean2[2],1))+r'_{'+str(round(tuc2_statsvmean2[1]-tuc2_statsvmean2[2],1))+r'('+str(round(tuc2_statsvmean2[0]-tuc2_statsvmean2[2],1))+r')}'+r'^{+'+str(round(tuc2_statsvmean2[3]-tuc2_statsvmean2[2],1))+r'(+'+str(round(tuc2_statsvmean2[4]-tuc2_statsvmean2[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvdisptwoexpanded}{$'+str(round(tuc2_statsvdisp2[2],1))+r'_{'+str(round(tuc2_statsvdisp2[1]-tuc2_statsvdisp2[2],1))+r'('+str(round(tuc2_statsvdisp2[0]-tuc2_statsvdisp2[2],1))+r')}'+r'^{+'+str(round(tuc2_statsvdisp2[3]-tuc2_statsvdisp2[2],1))+r'(+'+str(round(tuc2_statsvdisp2[4]-tuc2_statsvdisp2[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehmeantwoexpanded}{$'+str(round(tuc2_statsfehmean2[2],2))+r'_{'+str(round(tuc2_statsfehmean2[1]-tuc2_statsfehmean2[2],2))+r'('+str(round(tuc2_statsfehmean2[0]-tuc2_statsfehmean2[2],2))+r')}'+r'^{+'+str(round(tuc2_statsfehmean2[3]-tuc2_statsfehmean2[2],2))+r'(+'+str(round(tuc2_statsfehmean2[4]-tuc2_statsfehmean2[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehdisptwoexpanded}{$'+str(round(tuc2_statsfehdisp2[2],2))+r'_{'+str(round(tuc2_statsfehdisp2[1]-tuc2_statsfehdisp2[2],2))+r'('+str(round(tuc2_statsfehdisp2[0]-tuc2_statsfehdisp2[2],2))+r')}'+r'^{+'+str(round(tuc2_statsfehdisp2[3]-tuc2_statsfehdisp2[2],2))+r'(+'+str(round(tuc2_statsfehdisp2[4]-tuc2_statsfehdisp2[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvgradexpanded}{$'+str(round(tuc2_statsvgrad[2],1))+r'_{'+str(round(tuc2_statsvgrad[1]-tuc2_statsvgrad[2],1))+r'('+str(round(tuc2_statsvgrad[0]-tuc2_statsvgrad[2],1))+r')}'+r'^{+'+str(round(tuc2_statsvgrad[3]-tuc2_statsvgrad[2],1))+r'(+'+str(round(tuc2_statsvgrad[4]-tuc2_statsvgrad[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucvthetaexpanded}{$'+str(round(tuc2_statsvtheta[2],0))+r'_{'+str(round(tuc2_statsvtheta[1]-tuc2_statsvtheta[2],0))+r'('+str(round(tuc2_statsvtheta[0]-tuc2_statsvtheta[2],0))+r')}'+r'^{+'+str(round(tuc2_statsvtheta[3]-tuc2_statsvtheta[2],0))+r'(+'+str(round(tuc2_statsvtheta[4]-tuc2_statsvtheta[2],0))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\tucfehgradexpanded}{$'+str(round(tuc2_statsfehgrad[2],2))+r'_{'+str(round(tuc2_statsfehgrad[1]-tuc2_statsfehgrad[2],2))+r'('+str(round(tuc2_statsfehgrad[0]-tuc2_statsfehgrad[2],2))+r')}'+r'^{+'+str(round(tuc2_statsfehgrad[3]-tuc2_statsfehgrad[2],2))+r'(+'+str(round(tuc2_statsfehgrad[4]-tuc2_statsfehgrad[2],2))+r')}$'+r'}'+'\n')


g1.write(r'\newcommand{\grufmem}{$'+str(round(gru1_statsfmem[2],2))+r'_{'+str(round(gru1_statsfmem[1]-gru1_statsfmem[2],2))+r'}'+r'^{+'+str(round(gru1_statsfmem[3]-gru1_statsfmem[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvmean}{$'+str(round(gru1_statsvmean[2],1))+r'_{'+str(round(gru1_statsvmean[1]-gru1_statsvmean[2],1))+r'}'+r'^{+'+str(round(gru1_statsvmean[3]-gru1_statsvmean[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvdisp}{$'+str(round(gru1_statsvdisp[2],1))+r'_{'+str(round(gru1_statsvdisp[1]-gru1_statsvdisp[2],1))+r'}'+r'^{+'+str(round(gru1_statsvdisp[3]-gru1_statsvdisp[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehmean}{$'+str(round(gru1_statsfehmean[2],2))+r'_{'+str(round(gru1_statsfehmean[1]-gru1_statsfehmean[2],2))+r'}'+r'^{+'+str(round(gru1_statsfehmean[3]-gru1_statsfehmean[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehdisp}{$'+str(round(gru1_statsfehdisp[2],2))+r'_{'+str(round(gru1_statsfehdisp[1]-gru1_statsfehdisp[2],2))+r'}'+r'^{+'+str(round(gru1_statsfehdisp[3]-gru1_statsfehdisp[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvmeantwo}{$'+str(round(gru1_statsvmean2[2],1))+r'_{'+str(round(gru1_statsvmean2[1]-gru1_statsvmean2[2],1))+r'}'+r'^{+'+str(round(gru1_statsvmean2[3]-gru1_statsvmean2[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvdisptwo}{$'+str(round(gru1_statsvdisp2[2],1))+r'_{'+str(round(gru1_statsvdisp2[1]-gru1_statsvdisp2[2],1))+r'}'+r'^{+'+str(round(gru1_statsvdisp2[3]-gru1_statsvdisp2[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehmeantwo}{$'+str(round(gru1_statsfehmean2[2],2))+r'_{'+str(round(gru1_statsfehmean2[1]-gru1_statsfehmean2[2],2))+r'}'+r'^{+'+str(round(gru1_statsfehmean2[3]-gru1_statsfehmean2[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehdisptwo}{$'+str(round(gru1_statsfehdisp2[2],2))+r'_{'+str(round(gru1_statsfehdisp2[1]-gru1_statsfehdisp2[2],2))+r'}'+r'^{+'+str(round(gru1_statsfehdisp2[3]-gru1_statsfehdisp2[2],2))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvgrad}{$'+str(round(gru1_statsvgrad[2],1))+r'_{'+str(round(gru1_statsvgrad[1]-gru1_statsvgrad[2],1))+r'}'+r'^{+'+str(round(gru1_statsvgrad[3]-gru1_statsvgrad[2],1))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvtheta}{$'+str(round(gru1_statsvtheta[2],0))+r'_{'+str(round(gru1_statsvtheta[1]-gru1_statsvtheta[2],0))+r'}'+r'^{+'+str(round(gru1_statsvtheta[3]-gru1_statsvtheta[2],0))+r'}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehgrad}{$'+str(round(gru1_statsfehgrad[2],2))+r'_{'+str(round(gru1_statsfehgrad[1]-gru1_statsfehgrad[2],2))+r'}'+r'^{+'+str(round(gru1_statsfehgrad[3]-gru1_statsfehgrad[2],2))+r'}$'+r'}'+'\n')

g1.write(r'\newcommand{\grufmemexpanded}{$'+str(round(gru1_statsfmem[2],2))+r'_{'+str(round(gru1_statsfmem[1]-gru1_statsfmem[2],2))+r'('+str(round(gru1_statsfmem[0]-gru1_statsfmem[2],2))+r')}'+r'^{+'+str(round(gru1_statsfmem[3]-gru1_statsfmem[2],2))+r'(+'+str(round(gru1_statsfmem[4]-gru1_statsfmem[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvmeanexpanded}{$'+str(round(gru1_statsvmean[2],1))+r'_{'+str(round(gru1_statsvmean[1]-gru1_statsvmean[2],1))+r'('+str(round(gru1_statsvmean[0]-gru1_statsvmean[2],1))+r')}'+r'^{+'+str(round(gru1_statsvmean[3]-gru1_statsvmean[2],1))+r'(+'+str(round(gru1_statsvmean[4]-gru1_statsvmean[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvdispexpanded}{$'+str(round(gru1_statsvdisp[2],1))+r'_{'+str(round(gru1_statsvdisp[1]-gru1_statsvdisp[2],1))+r'('+str(round(gru1_statsvdisp[0]-gru1_statsvdisp[2],1))+r')}'+r'^{+'+str(round(gru1_statsvdisp[3]-gru1_statsvdisp[2],1))+r'(+'+str(round(gru1_statsvdisp[4]-gru1_statsvdisp[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehmeanexpanded}{$'+str(round(gru1_statsfehmean[2],2))+r'_{'+str(round(gru1_statsfehmean[1]-gru1_statsfehmean[2],2))+r'('+str(round(gru1_statsfehmean[0]-gru1_statsfehmean[2],2))+r')}'+r'^{+'+str(round(gru1_statsfehmean[3]-gru1_statsfehmean[2],2))+r'(+'+str(round(gru1_statsfehmean[4]-gru1_statsfehmean[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehdispexpanded}{$'+str(round(gru1_statsfehdisp[2],2))+r'_{'+str(round(gru1_statsfehdisp[1]-gru1_statsfehdisp[2],2))+r'('+str(round(gru1_statsfehdisp[0]-gru1_statsfehdisp[2],2))+r')}'+r'^{+'+str(round(gru1_statsfehdisp[3]-gru1_statsfehdisp[2],2))+r'(+'+str(round(gru1_statsfehdisp[4]-gru1_statsfehdisp[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvmeantwoexpanded}{$'+str(round(gru1_statsvmean2[2],1))+r'_{'+str(round(gru1_statsvmean2[1]-gru1_statsvmean2[2],1))+r'('+str(round(gru1_statsvmean2[0]-gru1_statsvmean2[2],1))+r')}'+r'^{+'+str(round(gru1_statsvmean2[3]-gru1_statsvmean2[2],1))+r'(+'+str(round(gru1_statsvmean2[4]-gru1_statsvmean2[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvdisptwoexpanded}{$'+str(round(gru1_statsvdisp2[2],1))+r'_{'+str(round(gru1_statsvdisp2[1]-gru1_statsvdisp2[2],1))+r'('+str(round(gru1_statsvdisp2[0]-gru1_statsvdisp2[2],1))+r')}'+r'^{+'+str(round(gru1_statsvdisp2[3]-gru1_statsvdisp2[2],1))+r'(+'+str(round(gru1_statsvdisp2[4]-gru1_statsvdisp2[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehmeantwoexpanded}{$'+str(round(gru1_statsfehmean2[2],2))+r'_{'+str(round(gru1_statsfehmean2[1]-gru1_statsfehmean2[2],2))+r'('+str(round(gru1_statsfehmean2[0]-gru1_statsfehmean2[2],2))+r')}'+r'^{+'+str(round(gru1_statsfehmean2[3]-gru1_statsfehmean2[2],2))+r'(+'+str(round(gru1_statsfehmean2[4]-gru1_statsfehmean2[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehdisptwoexpanded}{$'+str(round(gru1_statsfehdisp2[2],2))+r'_{'+str(round(gru1_statsfehdisp2[1]-gru1_statsfehdisp2[2],2))+r'('+str(round(gru1_statsfehdisp2[0]-gru1_statsfehdisp2[2],2))+r')}'+r'^{+'+str(round(gru1_statsfehdisp2[3]-gru1_statsfehdisp2[2],2))+r'(+'+str(round(gru1_statsfehdisp2[4]-gru1_statsfehdisp2[2],2))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvgradexpanded}{$'+str(round(gru1_statsvgrad[2],1))+r'_{'+str(round(gru1_statsvgrad[1]-gru1_statsvgrad[2],1))+r'('+str(round(gru1_statsvgrad[0]-gru1_statsvgrad[2],1))+r')}'+r'^{+'+str(round(gru1_statsvgrad[3]-gru1_statsvgrad[2],1))+r'(+'+str(round(gru1_statsvgrad[4]-gru1_statsvgrad[2],1))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\gruvthetaexpanded}{$'+str(round(gru1_statsvtheta[2],0))+r'_{'+str(round(gru1_statsvtheta[1]-gru1_statsvtheta[2],0))+r'('+str(round(gru1_statsvtheta[0]-gru1_statsvtheta[2],0))+r')}'+r'^{+'+str(round(gru1_statsvtheta[3]-gru1_statsvtheta[2],0))+r'(+'+str(round(gru1_statsvtheta[4]-gru1_statsvtheta[2],0))+r')}$'+r'}'+'\n')
g1.write(r'\newcommand{\grufehgradexpanded}{$'+str(round(gru1_statsfehgrad[2],2))+r'_{'+str(round(gru1_statsfehgrad[1]-gru1_statsfehgrad[2],2))+r'('+str(round(gru1_statsfehgrad[0]-gru1_statsfehgrad[2],2))+r')}'+r'^{+'+str(round(gru1_statsfehgrad[3]-gru1_statsfehgrad[2],2))+r'(+'+str(round(gru1_statsfehgrad[4]-gru1_statsfehgrad[2],2))+r')}$'+r'}'+'\n')



g1.write(r'\newcommand{\gruvdispupperlim}{$'+str(round(np.percentile(gru1_vdisp,84),1))+r'$}'+'\n')
g1.write(r'\newcommand{\tucvdispupperlim}{$'+str(round(np.percentile(tuc2_vdisp,84),1))+r'$}'+'\n')
g1.write(r'\newcommand{\grufehdispupperlim}{$'+str(round(np.percentile(gru1_fehdisp,84),1))+r'$}'+'\n')
g1.write(r'\newcommand{\tucfehdispupperlim}{$'+str(round(np.percentile(tuc2_fehdisp,84),1))+r'$}'+'\n')
g1.write(r'\newcommand{\gruvgradupperlim}{$'+str(round(np.percentile(gru1_vgrad,84),1))+r'$}'+'\n')
g1.write(r'\newcommand{\tucvgradupperlim}{$'+str(round(np.percentile(tuc2_vgrad,84),1))+r'$}'+'\n')
g1.write(r'\newcommand{\grufehgradlowerlim}{$'+str(round(np.percentile(gru1_fehgrad,16),1))+r'$}'+'\n')
g1.write(r'\newcommand{\tucfehgradlowerlim}{$'+str(round(np.percentile(tuc2_fehgrad,16),1))+r'$}'+'\n')

g2.write(r'\begin{table*}'+'\n')
g2.write(r'\scriptsize'+'\n')
g2.write(r'\centering'+'\n')
g2.write(r'\caption{Summary of probability distribution functions for chemodynamical parameters}'+'\n')
g2.write(r'\begin{tabular}{@{}lllllllllll@{}}'+'\n')
g2.write(r'\hline'+'\n')
g2.write(r'parameter & prior & posterior: Tuc 2 & posterior: Gru 1 & description\\'+'\n')
#g2.write(r'&  & (red sample) & (blue sample) &\\'+'\n')
#g2.write(r'&  & (red sample) &\\'+'\n')
g2.write(r'\hline'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$f_{\rm mem}$ & uniform between 0 and 1 & \tucfmemexpanded & \grufmemexpanded '+r'& member fraction' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\langle v_{\rm los}\rangle_{\rm mem}$ [km s$^{-1}$] & uniform between -160 and -110 & \tucvmeanexpanded & \gruvmeanexpanded '+r'& mean velocity at center (members)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\sigma_{v_{\rm los},\mathrm{mem}}$ [km s$^{-1}$] & uniform between 0 and +500 & \tucvdispexpanded & \gruvdispexpanded '+r'& velocity dispersion (members)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\langle \feh\rangle_{\rm mem} $ & uniform between -5 and -1 & \tucfehmeanexpanded & \grufehmeanexpanded '+r'& mean metallicity at center (members)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\sigma_{\feh,\mathrm{mem}}$ & uniform between 0 and +2 & \tucfehdispexpanded & \grufehdispexpanded '+r'& metallicity dispersion (members)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$k_{v_{\rm los}}$ [km s$^{-1}$ arcmin$^{-1}$] & uniform between 0 and +10 & \tucvgradexpanded & \gruvgradexpanded '+r'& magnitude of maximum velocity gradient (members)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\theta_{v_{\rm los}}$ [$\degr$] & uniform between -180 and +180 & \tucvthetaexpanded & \gruvthetaexpanded '+r'& direction of maximum velocity gradient (members)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$k_{\feh}$ [dex arcmin$^{-1}$] & uniform between -1 and 0 & \tucfehgradexpanded & \grufehgradexpanded '+r'& magnitude of metallicity gradient (members)' +r'\\'+'\n')
g2.write(r'$\langle v_{\rm los}\rangle_{\rm non}$ [km s$^{-1}$] & uniform between -500 and +500 & \tucvmeantwoexpanded & \gruvmeantwoexpanded '+r'& mean velocity (nonmembers)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\sigma_{v_{\rm los},\mathrm{non}}$ [km s$^{-1}$] & uniform between 0 and +500 & \tucvdisptwoexpanded & \gruvdisptwoexpanded '+r'& velocity dispersion (nonmembers)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\langle \feh\rangle_{\rm non} $ & uniform between -5 and +1 & \tucfehmeantwoexpanded & \grufehmeantwoexpanded '+r'& mean metallicity (nonmembers)' +r'\\'+'\n')
g2.write(r'\smallskip'+'\n')
g2.write(r'$\sigma_{\feh,\mathrm{non}}$ & uniform between 0 and +2 & \tucfehdisptwoexpanded & \grufehdisptwoexpanded '+r'& metallicity dispersion (nonmembers)' +r'\\'+'\n')
g2.write(r'\\'+'\n')

g2.write(r'\hline'+'\n')
g2.write(r'\end{tabular}'+'\n')
g2.write(r'\\'+'\n')
g2.write(r'\label{tab:tuc2gru1teffprior_mixture}'+'\n')
g2.write(r'\end{table*}'+'\n')



g1.close()
g2.close()
plotfilename='tuc2gru1teffprior_mixture.pdf'
plt.savefig(plotfilename,dpi=400)
plt.show()
plt.close()
