import numpy as np
import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
from astropy.io import fits 
from scipy import stats
import random
#import mycode2
np.set_printoptions(threshold='nan')

dsph=['car','dra','for','scl']
dsphname=['Carina','Draco','Fornax','Sculptor']
#dsph=['dra']
#dsphname=['Draco']

#plt.rc('grid',alpha=0.7) # modify rcparams
#plt.rc('grid',color='white')
#plt.rc('grid',linestyle='-')
plt.rc('legend',frameon='False')
plt.rc('xtick.major',size=1)
plt.rc('ytick.major',size=1)
plt.rc('axes',axisbelow='True')
plt.rc('axes',grid='False')
plt.rc('axes',facecolor='white')
plt.rc('axes',linewidth=0.2)
plt.rc('xtick.major',width=0.25)
plt.rc('ytick.major',width=0.25)
plt.rc('xtick',direction='in')
plt.rc('ytick',direction='in')
plt.rc('xtick',labelsize='4')
plt.rc('ytick',labelsize='4')
plt.rc('text',usetex='True')
plt.rc('font',family='serif')
plt.rc('font',style='normal')
plt.rc('font',serif='Century')
plt.rc('savefig',format='eps')
plt.rc('lines',markeredgewidth=0)
plt.rc('lines',markersize=2)
            
for i in range(0,len(dsph)):
    data1=dsph[i]+'_wp11post_equal_weights.dat'

    with open(data1) as f: # read data file
        data=f.readlines()

    data=random.sample(data,1000) # just take 1000 randomly-sampled points
    random.shuffle(data) # shuffle just to be sure they're not in any particular order
    rratio=[] # initialize arrays
    rhalf2=[]
    wmean1=[]
    deltaw=[]
    wvar1=[]
    wvar2=[]
    fsub=[]
    fmem=[]
    vvar1=[]
    vvar2=[]
    mualpha=[]
    mudelta=[]
    like=[]
    
    for line in data: # fill arrays
        p=line.split()
        rratio.append(float(p[0]))
        rhalf2.append(float(p[1]))
        wmean1.append(float(p[2]))
        deltaw.append(float(p[3]))
        wvar1.append(float(p[4]))
        wvar2.append(float(p[5]))
        fsub.append(float(p[6]))
        fmem.append(float(p[7]))
        vvar1.append(float(p[8]))
        vvar2.append(float(p[9]))
        mualpha.append(float(p[10]))
        mudelta.append(float(p[11]))
        like.append(float(p[12]))
            
    rratio=np.array(rratio) #convert to np arrays
    rhalf2=np.array(rhalf2)
    wmean1=np.array(wmean1)
    deltaw=np.array(deltaw)
    wvar1=np.array(wvar1)
    wvar2=np.array(wvar2)
    fsub=np.array(fsub)
    fmem=np.array(fmem)
    vvar1=np.array(vvar1)
    vvar2=np.array(vvar2)
    mualpha=np.array(mualpha)
    mudelta=np.array(mudelta)
    like=np.array(like)
    rhalf1=np.log10(rratio*10.**rhalf2)
    mwalker1=580.*rratio*(10.**rhalf2)*(10.**vvar1)
    mwalker2=580.*(10.**rhalf2)*(10.**vvar2)
    gamma=1.+np.log10((10.**vvar2)/(10.**vvar1))/np.log10((10.**rhalf2)/(10.**rhalf1))
    
#likenorm=(like-min(like))/(max(like)-min(like))
#likenorm=(like-max(like))/(min(like)-max(like))
    likenorm=np.argsort(like)/float(len(like))
#likenorm=matplotlib.colors.Normalize(vmin=np.min(like),vmax=np.max(like),clip=False)
    
    
    gs=plt.GridSpec(13,13) # define multi-panel plot
    gs.update(wspace=0,hspace=0) # specify inter-panel spacing
    fig=plt.figure(figsize=(6,6)) # define plot size
#fig.set_
    
    ax12_0=fig.add_subplot(gs[12,0])
    ax11_0=fig.add_subplot(gs[11,0])
    ax10_0=fig.add_subplot(gs[10,0])
    ax9_0=fig.add_subplot(gs[9,0])
    ax8_0=fig.add_subplot(gs[8,0])
    ax7_0=fig.add_subplot(gs[7,0])
    ax6_0=fig.add_subplot(gs[6,0])
    ax5_0=fig.add_subplot(gs[5,0])
    ax4_0=fig.add_subplot(gs[4,0])
    ax3_0=fig.add_subplot(gs[3,0])
    ax2_0=fig.add_subplot(gs[2,0])
    ax1_0=fig.add_subplot(gs[1,0])
    
    ax11_1=fig.add_subplot(gs[11,1])
    ax10_1=fig.add_subplot(gs[10,1])
    ax9_1=fig.add_subplot(gs[9,1])
    ax8_1=fig.add_subplot(gs[8,1])
    ax7_1=fig.add_subplot(gs[7,1])
    ax6_1=fig.add_subplot(gs[6,1])
    ax5_1=fig.add_subplot(gs[5,1])
    ax4_1=fig.add_subplot(gs[4,1])
    ax3_1=fig.add_subplot(gs[3,1])
    ax2_1=fig.add_subplot(gs[2,1])
    ax1_1=fig.add_subplot(gs[1,1])
    
    ax10_2=fig.add_subplot(gs[10,2])
    ax9_2=fig.add_subplot(gs[9,2])
    ax8_2=fig.add_subplot(gs[8,2])
    ax7_2=fig.add_subplot(gs[7,2])
    ax6_2=fig.add_subplot(gs[6,2])
    ax5_2=fig.add_subplot(gs[5,2])
    ax4_2=fig.add_subplot(gs[4,2])
    ax3_2=fig.add_subplot(gs[3,2])
    ax2_2=fig.add_subplot(gs[2,2])
    ax1_2=fig.add_subplot(gs[1,2])
    
    ax9_3=fig.add_subplot(gs[9,3])
    ax8_3=fig.add_subplot(gs[8,3])
    ax7_3=fig.add_subplot(gs[7,3])
    ax6_3=fig.add_subplot(gs[6,3])
    ax5_3=fig.add_subplot(gs[5,3])
    ax4_3=fig.add_subplot(gs[4,3])
    ax3_3=fig.add_subplot(gs[3,3])
    ax2_3=fig.add_subplot(gs[2,3])
    ax1_3=fig.add_subplot(gs[1,3])
    
    ax8_4=fig.add_subplot(gs[8,4])
    ax7_4=fig.add_subplot(gs[7,4])
    ax6_4=fig.add_subplot(gs[6,4])
    ax5_4=fig.add_subplot(gs[5,4])
    ax4_4=fig.add_subplot(gs[4,4])
    ax3_4=fig.add_subplot(gs[3,4])
    ax2_4=fig.add_subplot(gs[2,4])
    ax1_4=fig.add_subplot(gs[1,4])
    
    ax7_5=fig.add_subplot(gs[7,5])
    ax6_5=fig.add_subplot(gs[6,5])
    ax5_5=fig.add_subplot(gs[5,5])
    ax4_5=fig.add_subplot(gs[4,5])
    ax3_5=fig.add_subplot(gs[3,5])
    ax2_5=fig.add_subplot(gs[2,5])
    ax1_5=fig.add_subplot(gs[1,5])
    
    ax6_6=fig.add_subplot(gs[6,6])
    ax5_6=fig.add_subplot(gs[5,6])
    ax4_6=fig.add_subplot(gs[4,6])
    ax3_6=fig.add_subplot(gs[3,6])
    ax2_6=fig.add_subplot(gs[2,6])
    ax1_6=fig.add_subplot(gs[1,6])
    
    ax5_7=fig.add_subplot(gs[5,7])
    ax4_7=fig.add_subplot(gs[4,7])
    ax3_7=fig.add_subplot(gs[3,7])
    ax2_7=fig.add_subplot(gs[2,7])
    ax1_7=fig.add_subplot(gs[1,7])
    
    ax4_8=fig.add_subplot(gs[4,8])
    ax3_8=fig.add_subplot(gs[3,8])
    ax2_8=fig.add_subplot(gs[2,8])
    ax1_8=fig.add_subplot(gs[1,8])
    
    ax3_9=fig.add_subplot(gs[3,9])
    ax2_9=fig.add_subplot(gs[2,9])
    ax1_9=fig.add_subplot(gs[1,9])
    
    ax2_10=fig.add_subplot(gs[2,10])
    ax1_10=fig.add_subplot(gs[1,10])

    ax1_11=fig.add_subplot(gs[1,11])
    ax1_12=fig.add_subplot(gs[1,12])
    
    ax0_11=fig.add_subplot(gs[0,11])
    ax0_10=fig.add_subplot(gs[0,10])
    ax0_9=fig.add_subplot(gs[0,9])
    ax0_8=fig.add_subplot(gs[0,8])
    ax0_7=fig.add_subplot(gs[0,7])
    ax0_6=fig.add_subplot(gs[0,6])
    ax0_5=fig.add_subplot(gs[0,5])
    ax0_4=fig.add_subplot(gs[0,4])
    ax0_3=fig.add_subplot(gs[0,3])
    ax0_2=fig.add_subplot(gs[0,2])
    ax0_1=fig.add_subplot(gs[0,1])
    ax0_0=fig.add_subplot(gs[0,0])
    
    ax0_11=fig.add_subplot(gs[0,11])
#    ax0_12=fig.add_subplot(gs[0,12])
    
    rratiolim=[0,1]
    rhalf2lim=[0,4]
    wmean1lim=[-5,1]
    deltawlim=[0,3]
    wvar1lim=[-5,1]
    wvar2lim=[-5,1]
    fsublim=[0,1]
    fmemlim=[0,1]
    vvar1lim=[-5,5]
    vvar2lim=[-5,5]
    mualphalim=[-1000,1000]
    mudeltalim=[-1000,1000]       
    gammalim=[0,10]
    
    rratioprior=np.random.uniform(low=rratiolim[0],high=rratiolim[1],size=len(rratio))
    rhalf2prior=np.random.uniform(low=rhalf2lim[0],high=rhalf2lim[1],size=len(rhalf2))
    wmean1prior=np.random.uniform(low=wmean1lim[0],high=wmean1lim[1],size=len(wmean1))
    deltawprior=np.random.uniform(low=deltawlim[0],high=deltawlim[1],size=len(deltaw))
    wvar1prior=np.random.uniform(low=wvar1lim[0],high=wvar1lim[1],size=len(wvar1))
    wvar2prior=np.random.uniform(low=wvar2lim[0],high=wvar2lim[1],size=len(wvar2))
    fsubprior=np.random.uniform(low=fsublim[0],high=fsublim[1],size=len(fsub))
    fmemprior=np.random.uniform(low=fmemlim[0],high=fmemlim[1],size=len(fmem))
    vvar1prior=np.random.uniform(low=vvar1lim[0],high=vvar1lim[1],size=len(vvar1))
    vvar2prior=np.random.uniform(low=vvar2lim[0],high=vvar2lim[1],size=len(vvar2))
    mualphaprior=np.random.uniform(low=mualphalim[0],high=mualphalim[1],size=len(mualpha))
    mudeltaprior=np.random.uniform(low=mudeltalim[0],high=mudeltalim[1],size=len(mudelta))
    rhalf1prior=np.log10(rratioprior*10.**rhalf2prior)
    mwalker1prior=580.*rratioprior*(10.**rhalf2prior)*(10.**vvar1prior)
    mwalker2prior=580.*(10.**rhalf2prior)*(10.**vvar2prior)
    gammaprior=1.+np.log10((10.**vvar2prior)/(10.**vvar1prior))/np.log10((10.**rhalf2prior)/(10.**rhalf1prior))
    
    rratiolabel=[r'$\frac{R_{\rm h_1}}{R_{\rm h_2}}$']
    rhalf2label=[r'$\log\bigl [\frac{R_{\rm h_2}}{\mathrm{pc}}\bigr ]$']
    fmemlabel=[r'$f_{\rm mem}$']
    fsublabel=[r'$f_{\rm sub}$']
    wmean1label=[r'$\overline{[\mathrm{Fe/H}]}_1$']
    deltawlabel=[r'$\Delta \overline{[\mathrm{Fe/H}]}$']
    wvar1label=[r'$\log\bigl [\sigma^2_{[\mathrm{Fe/H}]_1}\bigr]$']
    wvar1label=[r'$\log[\sigma^2_{[\mathrm{Fe/H}]_1}]$']
    wvar2label=[r'$\log [\sigma^2_{[\mathrm{Fe/H}]_2}]$']
    vvar1label=[r'$\log\bigl [\frac{\sigma^2_{v_1}}{\mathrm{km/s}}\bigr]$']
    vvar2label=[r'$\log\bigl[\frac{\sigma^2_{v_2}}{\mathrm{km/s}}\bigr]$']
    mualphalabel=[r'$\mu_{\alpha}  [\frac{\rm mas}{\rm cent}]$']
    mudeltalabel=[r'$\mu_{\delta}  [\frac{\rm mas}{\rm cent}]$']
    gammalabel=[r'$\Gamma_{\rm obs}$']

    rratioticks=[0.25,0.5,0.75]
    rhalf2ticks=[1,2,3]
    fmemticks=[0.25,0.5,0.75]
    fsubticks=[0.25,0.5,0.75]
    wmean1ticks=[-4,-3,-2,-1,0]
    deltawticks=[1,2]
    wvar1ticks=[-4,-3,-2,-1,0]
    wvar2ticks=[-4,-3,-2,-1,0]
    vvar1ticks=[-4,-2,0,2,4]
    vvar2ticks=[-4,-2,0,2,4]
    mualphaticks=[-500,0,500]
    mudeltaticks=[-500,0,500]
    gammaticks=[2,4,6,8]
    
    colmap=plt.get_cmap("Greys")
    
    ax12_0.yaxis.set_label_coords(-0.9,0.35)
    ax12_0.set_xlabel(fmemlabel[0],fontsize=4.5,rotation=0)
    ax12_0.set_ylabel(fsublabel[0],fontsize=4.5,rotation=0,labelpad=10)
    ax12_0.set_xlim(fmemlim)
    ax12_0.set_ylim(fsublim)
    ax12_0.set_xscale(u'linear')
    ax12_0.set_yscale(u'linear')
    ax12_0.set_xticks([0]+fmemticks+[1])
    ax12_0.set_xticklabels([0]+fmemticks+[1],rotation=90)
    ax12_0.set_yticks([0]+fsubticks)
    kde=stats.gaussian_kde([fmem,fsub])
    density=kde([fmem,fsub])
    ax12_0.scatter(fmemprior,fsubprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax12_0.scatter(fmem,fsub,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax11_0.yaxis.set_label_coords(-0.9,0.3)
#ax10_0.set_xlabel(rratiolabel,fontsize=4.5,rotation=-30)
    ax11_0.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=0,labelpad=10)
    ax11_0.set_xlim(fmemlim)
    ax11_0.set_ylim(rratiolim)
    ax11_0.set_xscale(u'linear')
    ax11_0.set_yscale(u'linear')
    ax11_0.set_xticks(fmemticks)
    ax11_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax11_0.set_yticks(rratioticks)
    kde=stats.gaussian_kde([fmem,rratio])
    density=kde([fmem,rratio])
    ax11_0.scatter(fmemprior,rratioprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax11_0.scatter(fmem,rratio,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax10_0.yaxis.set_label_coords(-1,0.2)
#ax9_0.set_xlabel(rhalf2label,fontsize=4.5,rotation=-30)
    ax10_0.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=0,labelpad=15)
    ax10_0.set_xlim(fmemlim)
    ax10_0.set_ylim(rhalf2lim)
    ax10_0.set_xscale(u'linear')
    ax10_0.set_yscale(u'linear')
    ax10_0.set_xticks(fmemticks)
    ax10_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax10_0.set_yticks(rhalf2ticks)
    kde=stats.gaussian_kde([fmem,rhalf2])
    density=kde([fmem,rhalf2])
    ax10_0.scatter(fmemprior,rhalf2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax10_0.scatter(fmem,rhalf2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax9_0.yaxis.set_label_coords(-1,0.4)
#ax8_0.set_xlabel(wmean1label,fontsize=4.5,rotation=-30)
    ax9_0.set_ylabel(wmean1label[0],fontsize=4.5,rotation=0,labelpad=10)
    ax9_0.set_xlim(fmemlim)
    ax9_0.set_ylim(wmean1lim)
    ax9_0.set_xscale(u'linear')
    ax9_0.set_yscale(u'linear')
    ax9_0.set_xticks(fmemticks)
    ax9_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax9_0.set_yticks(wmean1ticks)
    kde=stats.gaussian_kde([fmem,wmean1])
    density=kde([fmem,wmean1])
    ax9_0.scatter(fmemprior,wmean1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax9_0.scatter(fmem,wmean1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax8_0.yaxis.set_label_coords(-1,0.4)
#ax7_0.set_xlabel(deltawlabel,fontsize=4.5,rotation=-30)
    ax8_0.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=0,labelpad=15)
    ax8_0.set_xlim(fmemlim)
    ax8_0.set_ylim(deltawlim)
    ax8_0.set_xscale(u'linear')
    ax8_0.set_yscale(u'linear')
    ax8_0.set_xticks(fmemticks)
    ax8_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax8_0.set_yticks(deltawticks)
    kde=stats.gaussian_kde([fmem,deltaw])
    density=kde([fmem,deltaw])
    ax8_0.scatter(fmemprior,deltawprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax8_0.scatter(fmem,deltaw,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax7_0.yaxis.set_label_coords(-1.1,0.35)
#ax6_0.set_xlabel(wvar1label,fontsize=4.5,rotation=-30)
    ax7_0.set_ylabel(wvar1label[0],fontsize=4.5,rotation=0,labelpad=15)
    ax7_0.set_xlim(fmemlim)
    ax7_0.set_ylim(wvar1lim)
    ax7_0.set_xscale(u'linear')
    ax7_0.set_yscale(u'linear')
    ax7_0.set_xticks(fmemticks)
    ax7_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax7_0.set_yticks(wvar1ticks)
    kde=stats.gaussian_kde([fmem,wvar1])
    density=kde([fmem,wvar1])
    ax7_0.scatter(fmemprior,wvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax7_0.scatter(fmem,wvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax6_0.yaxis.set_label_coords(-1.1,0.35)
#ax5_0.set_xlabel(wvar2label,fontsize=4.5,rotation=-30)
    ax6_0.set_ylabel(wvar2label[0],fontsize=4.5,rotation=0,labelpad=15)
    ax6_0.set_xlim(fmemlim)
    ax6_0.set_ylim(wvar2lim)
    ax6_0.set_xscale(u'linear')
    ax6_0.set_yscale(u'linear')
    ax6_0.set_xticks(fmemticks)
    ax6_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_0.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([fmem,wvar2])
    density=kde([fmem,wvar2])
    ax6_0.scatter(fmemprior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_0.scatter(fmem,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax5_0.yaxis.set_label_coords(-1.1,0.2)
#ax4_0.set_xlabel(vvar1label,fontsize=4.5,rotation=-30)
    ax5_0.set_ylabel(vvar1label[0],fontsize=4.5,rotation=0,labelpad=15)
    ax5_0.set_xlim(fmemlim)
    ax5_0.set_ylim(vvar1lim)
    ax5_0.set_xscale(u'linear')
    ax5_0.set_yscale(u'linear')
    ax5_0.set_xticks(fmemticks)
    ax5_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_0.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([fmem,vvar1])
    density=kde([fmem,vvar1])
    ax5_0.scatter(fmemprior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_0.scatter(fmem,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax4_0.yaxis.set_label_coords(-1.1,0.2)
#ax3_0.set_xlabel(vvar2label,fontsize=4.5,rotation=-30)
    ax4_0.set_ylabel(vvar2label[0],fontsize=4.5,rotation=0,labelpad=15)
    ax4_0.set_xlim(fmemlim)
    ax4_0.set_ylim(vvar2lim)
    ax4_0.set_xscale(u'linear')
    ax4_0.set_yscale(u'linear')
    ax4_0.set_xticks(fmemticks)
    ax4_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_0.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([fmem,vvar2])
    density=kde([fmem,vvar2])
    ax4_0.scatter(fmemprior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_0.scatter(fmem,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax3_0.yaxis.set_label_coords(-1.1,0.35)
#ax2_0.set_xlabel(mualphalabel,fontsize=4.5,rotation=-30)
    ax3_0.set_ylabel(mualphalabel[0],fontsize=4.5,rotation=0,labelpad=10)
    ax3_0.set_xlim(fmemlim)
    ax3_0.set_ylim(mualphalim)
    ax3_0.set_xscale(u'linear')
    ax3_0.set_yscale(u'linear')
    ax3_0.set_xticks(fmemticks)
    ax3_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_0.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([fmem,mualpha])
    density=kde([fmem,mualpha])
    ax3_0.scatter(fmemprior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_0.scatter(fmem,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax2_0.yaxis.set_label_coords(-1.1,0.35)
#ax1_0.set_xlabel(mudeltalabel,fontsize=4.5,rotation=-30)
    ax2_0.set_ylabel(mudeltalabel[0],fontsize=4.5,rotation=0,labelpad=10)
    ax2_0.set_xlim(fmemlim)
    ax2_0.set_ylim(mudeltalim)
    ax2_0.set_xscale(u'linear')
    ax2_0.set_yscale(u'linear')
    ax2_0.set_xticks(fmemticks)
    ax2_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_0.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([fmem,mudelta])
    density=kde([fmem,mudelta])
    ax2_0.scatter(fmemprior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_0.scatter(fmem,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_0.yaxis.set_label_coords(-0.7,0.45)
#ax1_0.set_xlabel(gammalabel,fontsize=4.5,rotation=-30)
    ax1_0.set_ylabel(gammalabel[0],fontsize=4.5,rotation=0,labelpad=10)
    ax1_0.set_xlim(fmemlim)
    ax1_0.set_ylim(gammalim)
    ax1_0.set_xscale(u'linear')
    ax1_0.set_yscale(u'linear')
    ax1_0.set_xticks(fmemticks)
    ax1_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_0.set_yticks(gammaticks)
    kde=stats.gaussian_kde([fmem,gamma])
    density=kde([fmem,gamma])
    ax1_0.scatter(fmemprior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_0.scatter(fmem,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_0.set_xticks(fmemticks)
    ax0_0.set_ylabel('probability',fontsize=4.5,rotation=0,labelpad=15)
    ax0_0.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_0.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_0.hist(fmem,bins=50,range=fmemlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_0.hist(fmemprior,bins=50,range=fmemlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25,label="Prior")
    ax0_0.hist(fmem,bins=50,range=fmemlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25,label="Post.")
#    ax0_0.legend(loc=4,fontsize=7,shadow='False',handlelength=3)


    ax0_0.set_title(dsphname[i],loc='left',fontsize=7)
    
    
    ax11_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax11_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=0)
    ax11_1.set_xlim(fsublim)
    ax11_1.set_ylim(fsublim)
    ax11_1.set_xscale(u'linear')
    ax11_1.set_yscale(u'linear')
    ax11_1.set_xticks(fsubticks+[1])
    ax11_1.set_xticklabels(fsubticks+[1],rotation=90)
#ax11_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax11_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax11_1.set_yticks(rratioticks)
    kde=stats.gaussian_kde([fsub,rratio])
    density=kde([fsub,rratio])
    ax11_1.scatter(fsubprior,rratioprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax11_1.scatter(fsub,rratio,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax9_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax9_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax10_1.set_xlim(fsublim)
    ax10_1.set_ylim(rhalf2lim)
    ax10_1.set_xscale(u'linear')
    ax10_1.set_yscale(u'linear')
    ax10_1.set_xticks(fsubticks+[1])
    ax10_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax10_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax10_1.set_yticks(rhalf2ticks)
    kde=stats.gaussian_kde([fsub,rhalf2])
    density=kde([fsub,rhalf2])
    ax10_1.scatter(fsubprior,rhalf2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax10_1.scatter(fsub,rhalf2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax8_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax8_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax9_1.set_xlim(fsublim)
    ax9_1.set_ylim(wmean1lim)
    ax9_1.set_xscale(u'linear')
    ax9_1.set_yscale(u'linear')
    ax9_1.set_xticks(fsubticks+[1])
    ax9_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax9_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax9_1.set_yticks(wmean1ticks)
    kde=stats.gaussian_kde([fsub,wmean1])
    density=kde([fsub,wmean1])
    ax9_1.scatter(fsubprior,wmean1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax9_1.scatter(fsub,wmean1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax7_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax7_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax8_1.set_xlim(fsublim)
    ax8_1.set_ylim(deltawlim)
    ax8_1.set_xscale(u'linear')
    ax8_1.set_yscale(u'linear')
    ax8_1.set_xticks(fsubticks+[1])
    ax8_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax8_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax8_1.set_yticks(deltawticks)
    kde=stats.gaussian_kde([fsub,deltaw])
    density=kde([fsub,deltaw])
    ax8_1.scatter(fsubprior,deltawprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax8_1.scatter(fsub,deltaw,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax6_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax6_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax7_1.set_xlim(fsublim)
    ax7_1.set_ylim(wvar1lim)
    ax7_1.set_xscale(u'linear')
    ax7_1.set_yscale(u'linear')
    ax7_1.set_xticks(fsubticks+[1])
    ax7_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax7_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax7_1.set_yticks(wvar1ticks)
    kde=stats.gaussian_kde([fsub,wvar1])
    density=kde([fsub,wvar1])
    ax7_1.scatter(fsubprior,wvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax7_1.scatter(fsub,wvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax5_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax5_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax6_1.set_xlim(fsublim)
    ax6_1.set_ylim(wvar2lim)
    ax6_1.set_xscale(u'linear')
    ax6_1.set_yscale(u'linear')
    ax6_1.set_xticks(fsubticks+[1])
    ax6_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax6_1.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([fsub,wvar2])
    density=kde([fsub,wvar2])
    ax6_1.scatter(fsubprior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_1.scatter(fsub,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax4_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax4_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax5_1.set_xlim(fsublim)
    ax5_1.set_ylim(vvar1lim)
    ax5_1.set_xscale(u'linear')
    ax5_1.set_yscale(u'linear')
    ax5_1.set_xticks(fsubticks+[1])
    ax5_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_1.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([fsub,vvar1])
    density=kde([fsub,vvar1])
    ax5_1.scatter(fsubprior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_1.scatter(fsub,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax3_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax4_1.set_xlim(fsublim)
    ax4_1.set_ylim(vvar2lim)
    ax4_1.set_xscale(u'linear')
    ax4_1.set_yscale(u'linear')
    ax4_1.set_xticks(fsubticks+[1])
    ax4_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_1.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([fsub,vvar2])
    density=kde([fsub,vvar2])
    ax4_1.scatter(fsubprior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_1.scatter(fsub,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax2_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax3_1.set_xlim(fsublim)
    ax3_1.set_ylim(mualphalim)
    ax3_1.set_xscale(u'linear')
    ax3_1.set_yscale(u'linear')
    ax3_1.set_xticks(fsubticks+[1])
    ax3_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_1.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([fsub,mualpha])
    density=kde([fsub,mualpha])
    ax3_1.scatter(fsubprior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_1.scatter(fsub,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_1.set_xlabel(fsublabel[0],fontsize=4.5,rotation=0)
#ax1_1.set_ylabel(fsublabel[0],fontsize=4.5,rotation=90)
    ax2_1.set_xlim(fsublim)
    ax2_1.set_ylim(mudeltalim)
    ax2_1.set_xscale(u'linear')
    ax2_1.set_yscale(u'linear')
    ax2_1.set_xticks(fsubticks+[1])
    ax2_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_1.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([fsub,mudelta])
    density=kde([fsub,mudelta])
    ax2_1.scatter(fsubprior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_1.scatter(fsub,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_1.set_xlim(fsublim)
    ax1_1.set_ylim(gammalim)
    ax1_1.set_xscale(u'linear')
    ax1_1.set_yscale(u'linear')
    ax1_1.set_xticks(fsubticks+[1])
    ax1_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_1.set_yticks(gammaticks)
    kde=stats.gaussian_kde([fsub,gamma])
    density=kde([fsub,gamma])
    ax1_1.scatter(fsubprior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_1.scatter(fsub,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_1.set_xticks(fsubticks+[1])
    ax0_1.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_1.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_1.hist(fsub,bins=50,range=fsublim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_1.hist(fsubprior,bins=50,range=fsublim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_1.hist(fsub,bins=50,range=fsublim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax10_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax9_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax10_2.set_xlim(rratiolim)
    ax10_2.set_ylim(rhalf2lim)
    ax10_2.set_xscale(u'linear')
    ax10_2.set_yscale(u'linear')
    ax10_2.set_xticks(rratioticks+[1])
    ax10_2.set_xticklabels(rratioticks,rotation=90)
#ax9_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax10_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax10_2.set_yticks(rhalf2ticks)
    kde=stats.gaussian_kde([rratio,rhalf2])
    density=kde([rratio,rhalf2])
    ax10_2.scatter(rratioprior,rhalf2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax10_2.scatter(rratio,rhalf2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax8_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax8_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax9_2.set_xlim(rratiolim)
    ax9_2.set_ylim(wmean1lim)
    ax9_2.set_xscale(u'linear')
    ax9_2.set_yscale(u'linear')
    ax9_2.set_xticks(rratioticks+[1])
    ax9_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax9_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax9_2.set_yticks(wmean1ticks)
    kde=stats.gaussian_kde([rratio,wmean1])
    density=kde([rratio,wmean1])
    ax9_2.scatter(rratioprior,wmean1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax9_2.scatter(rratio,wmean1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax7_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax7_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax8_2.set_xlim(rratiolim)
    ax8_2.set_ylim(deltawlim)
    ax8_2.set_xscale(u'linear')
    ax8_2.set_yscale(u'linear')
    ax8_2.set_xticks(rratioticks+[1])
    ax8_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax8_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax8_2.set_yticks(deltawticks)
    kde=stats.gaussian_kde([rratio,deltaw])
    density=kde([rratio,deltaw])
    ax8_2.scatter(rratioprior,deltawprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax8_2.scatter(rratio,deltaw,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax6_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax6_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax7_2.set_xlim(rratiolim)
    ax7_2.set_ylim(wvar1lim)
    ax7_2.set_xscale(u'linear')
    ax7_2.set_yscale(u'linear')
    ax7_2.set_xticks(rratioticks+[1])
    ax7_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax7_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax7_2.set_yticks(wvar1ticks)
    kde=stats.gaussian_kde([rratio,wvar1])
    density=kde([rratio,wvar1])
    ax7_2.scatter(rratioprior,wvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax7_2.scatter(rratio,wvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax5_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax5_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax6_2.set_xlim(rratiolim)
    ax6_2.set_ylim(wvar2lim)
    ax6_2.set_xscale(u'linear')
    ax6_2.set_yscale(u'linear')
    ax6_2.set_xticks(rratioticks+[1])
    ax6_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax6_2.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([rratio,wvar2])
    density=kde([rratio,wvar2])
    ax6_2.scatter(rratioprior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_2.scatter(rratio,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax4_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax4_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax5_2.set_xlim(rratiolim)
    ax5_2.set_ylim(vvar1lim)
    ax5_2.set_xscale(u'linear')
    ax5_2.set_yscale(u'linear')
    ax5_2.set_xticks(rratioticks+[1])
    ax5_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_2.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([rratio,vvar1])
    density=kde([rratio,vvar1])
    ax5_2.scatter(rratioprior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_2.scatter(rratio,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax3_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax4_2.set_xlim(rratiolim)
    ax4_2.set_ylim(vvar2lim)
    ax4_2.set_xscale(u'linear')
    ax4_2.set_yscale(u'linear')
    ax4_2.set_xticks(rratioticks+[1])
    ax4_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_2.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([rratio,vvar2])
    density=kde([rratio,vvar2])
    ax4_2.scatter(rratioprior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_2.scatter(rratio,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax2_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax3_2.set_xlim(rratiolim)
    ax3_2.set_ylim(mualphalim)
    ax3_2.set_xscale(u'linear')
    ax3_2.set_yscale(u'linear')
    ax3_2.set_xticks(rratioticks+[1])
    ax3_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_2.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([rratio,mualpha])
    density=kde([rratio,mualpha])
    ax3_2.scatter(rratioprior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_2.scatter(rratio,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_2.set_xlabel(rratiolabel[0],fontsize=4.5,rotation=0)
#ax1_2.set_ylabel(rratiolabel[0],fontsize=4.5,rotation=90)
    ax2_2.set_xlim(rratiolim)
    ax2_2.set_ylim(mudeltalim)
    ax2_2.set_xscale(u'linear')
    ax2_2.set_yscale(u'linear')
    ax2_2.set_xticks(rratioticks+[1])
    ax2_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_2.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([rratio,mudelta])
    density=kde([rratio,mudelta])
    ax2_2.scatter(rratioprior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_2.scatter(rratio,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_2.set_xlim(rratiolim)
    ax1_2.set_ylim(gammalim)
    ax1_2.set_xscale(u'linear')
    ax1_2.set_yscale(u'linear')
    ax1_2.set_xticks(rratioticks+[1])
    ax1_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_2.set_yticks(gammaticks)
    kde=stats.gaussian_kde([rratio,gamma])
    density=kde([rratio,gamma])
    ax1_2.scatter(rratioprior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_2.scatter(rratio,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_2.set_xticks(rratioticks+[1])
    ax0_2.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_2.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_2.hist(rratio,bins=50,range=rratiolim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_2.hist(rratioprior,bins=50,range=rratiolim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_2.hist(rratio,bins=50,range=rratiolim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax9_3.xaxis.set_label_coords(0.62,-0.4)
    ax9_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax8_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax9_3.set_xlim(rhalf2lim)
    ax9_3.set_ylim(wmean1lim)
    ax8_3.set_xscale(u'linear')
    ax9_3.set_yscale(u'linear')
    ax9_3.set_xticks(rhalf2ticks+[4])
    ax9_3.set_xticklabels(rhalf2ticks+[4],rotation=90)
#ax8_3xaxis.set_major_formatter(plt.NullFormatter())
    ax9_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax9_3.set_yticks(wmean1ticks)
    kde=stats.gaussian_kde([rhalf2,wmean1])
    density=kde([rhalf2,wmean1])
    ax9_3.scatter(rhalf2prior,wmean1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax9_3.scatter(rhalf2,wmean1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax7_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax7_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax8_3.set_xlim(rhalf2lim)
    ax8_3.set_ylim(deltawlim)
    ax8_3.set_xscale(u'linear')
    ax8_3.set_yscale(u'linear')
    ax8_3.set_xticks(rhalf2ticks+[1])
    ax8_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax8_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax8_3.set_yticks(deltawticks)
    kde=stats.gaussian_kde([rhalf2,deltaw])
    density=kde([rhalf2,deltaw])
    ax8_3.scatter(rhalf2prior,deltawprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax8_3.scatter(rhalf2,deltaw,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax6_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax6_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax7_3.set_xlim(rhalf2lim)
    ax7_3.set_ylim(wvar1lim)
    ax7_3.set_xscale(u'linear')
    ax7_3.set_yscale(u'linear')
    ax7_3.set_xticks(rhalf2ticks+[1])
    ax7_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax7_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax7_3.set_yticks(wvar1ticks)
    kde=stats.gaussian_kde([rhalf2,wvar1])
    density=kde([rhalf2,wvar1])
    ax7_3.scatter(rhalf2prior,wvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax7_3.scatter(rhalf2,wvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax5_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax5_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax6_3.set_xlim(rhalf2lim)
    ax6_3.set_ylim(wvar2lim)
    ax6_3.set_xscale(u'linear')
    ax6_3.set_yscale(u'linear')
    ax6_3.set_xticks(rhalf2ticks+[1])
    ax6_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax6_3.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([rhalf2,wvar2])
    density=kde([rhalf2,wvar2])
    ax6_3.scatter(rhalf2prior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_3.scatter(rhalf2,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax4_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax4_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax5_3.set_xlim(rhalf2lim)
    ax5_3.set_ylim(vvar1lim)
    ax5_3.set_xscale(u'linear')
    ax5_3.set_yscale(u'linear')
    ax5_3.set_xticks(rhalf2ticks+[1])
    ax5_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_3.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([rhalf2,vvar1])
    density=kde([rhalf2,vvar1])
    ax5_3.scatter(rhalf2prior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_3.scatter(rhalf2,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax3_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax4_3.set_xlim(rhalf2lim)
    ax4_3.set_ylim(vvar2lim)
    ax4_3.set_xscale(u'linear')
    ax4_3.set_yscale(u'linear')
    ax4_3.set_xticks(rhalf2ticks+[1])
    ax4_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_3.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([rhalf2,vvar2])
    density=kde([rhalf2,vvar2])
    ax4_3.scatter(rhalf2prior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_3.scatter(rhalf2,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax2_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax3_3.set_xlim(rhalf2lim)
    ax3_3.set_ylim(mualphalim)
    ax3_3.set_xscale(u'linear')
    ax3_3.set_yscale(u'linear')
    ax3_3.set_xticks(rhalf2ticks+[1])
    ax3_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_3.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([rhalf2,mualpha])
    density=kde([rhalf2,mualpha])
    ax3_3.scatter(rhalf2prior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_3.scatter(rhalf2,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_3.set_xlabel(rhalf2label[0],fontsize=4.5,rotation=0)
#ax1_3.set_ylabel(rhalf2label[0],fontsize=4.5,rotation=90)
    ax2_3.set_xlim(rhalf2lim)
    ax2_3.set_ylim(mudeltalim)
    ax2_3.set_xscale(u'linear')
    ax2_3.set_yscale(u'linear')
    ax2_3.set_xticks(rhalf2ticks+[1])
    ax2_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_3.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([rhalf2,mudelta])
    density=kde([rhalf2,mudelta])
    ax2_3.scatter(rhalf2prior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_3.scatter(rhalf2,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_3.set_xlim(rhalf2lim)
    ax1_3.set_ylim(gammalim)
    ax1_3.set_xscale(u'linear')
    ax1_3.set_yscale(u'linear')
    ax1_3.set_xticks(rhalf2ticks+[1])
    ax1_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_3.set_yticks(gammaticks)
    kde=stats.gaussian_kde([rhalf2,gamma])
    density=kde([rhalf2,gamma])
    ax1_3.scatter(rhalf2prior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_3.scatter(rhalf2,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_3.set_xticks(rhalf2ticks+[1])
    ax0_3.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_3.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_3.hist(rhalf2,bins=50,range=rhalf2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_3.hist(rhalf2prior,bins=50,range=rhalf2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_3.hist(rhalf2,bins=50,range=rhalf2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax8_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax7_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax8_4.set_xlim(wmean1lim)
    ax8_4.set_ylim(deltawlim)
    ax8_4.set_xscale(u'linear')
    ax8_4.set_yscale(u'linear')
    ax8_4.set_xticks(wmean1ticks+[1])
    ax8_4.set_xticklabels(wmean1ticks+[1],rotation=90)
#ax7_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax8_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax8_4.set_yticks(deltawticks)
    kde=stats.gaussian_kde([wmean1,deltaw])
    density=kde([wmean1,deltaw])
    ax8_4.scatter(wmean1prior,deltawprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax8_4.scatter(wmean1,deltaw,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax6_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax6_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax7_4.set_xlim(wmean1lim)
    ax7_4.set_ylim(wvar1lim)
    ax7_4.set_xscale(u'linear')
    ax7_4.set_yscale(u'linear')
    ax7_4.set_xticks(wmean1ticks+[1])
    ax7_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax7_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax7_4.set_yticks(wvar1ticks)
    kde=stats.gaussian_kde([wmean1,wvar1])
    density=kde([wmean1,wvar1])
    ax7_4.scatter(wmean1prior,wvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax7_4.scatter(wmean1,wvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax5_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax5_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax6_4.set_xlim(wmean1lim)
    ax6_4.set_ylim(wvar2lim)
    ax6_4.set_xscale(u'linear')
    ax6_4.set_yscale(u'linear')
    ax6_4.set_xticks(wmean1ticks+[1])
    ax6_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax6_4.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([wmean1,wvar2])
    density=kde([wmean1,wvar2])
    ax6_4.scatter(wmean1prior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_4.scatter(wmean1,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax4_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax4_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax5_4.set_xlim(wmean1lim)
    ax5_4.set_ylim(vvar1lim)
    ax5_4.set_xscale(u'linear')
    ax5_4.set_yscale(u'linear')
    ax5_4.set_xticks(wmean1ticks+[1])
    ax5_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_4.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([wmean1,vvar1])
    density=kde([wmean1,vvar1])
    ax5_4.scatter(wmean1prior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_4.scatter(wmean1,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax3_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax4_4.set_xlim(wmean1lim)
    ax4_4.set_ylim(vvar2lim)
    ax4_4.set_xscale(u'linear')
    ax4_4.set_yscale(u'linear')
    ax4_4.set_xticks(wmean1ticks+[1])
    ax4_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_4.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([wmean1,vvar2])
    density=kde([wmean1,vvar2])
    ax4_4.scatter(wmean1prior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_4.scatter(wmean1,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax2_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax3_4.set_xlim(wmean1lim)
    ax3_4.set_ylim(mualphalim)
    ax3_4.set_xscale(u'linear')
    ax3_4.set_yscale(u'linear')
    ax3_4.set_xticks(wmean1ticks+[1])
    ax3_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_4.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([wmean1,mualpha])
    density=kde([wmean1,mualpha])
    ax3_4.scatter(wmean1prior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_4.scatter(wmean1,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_4.set_xlabel(wmean1label[0],fontsize=4.5,rotation=0)
#ax1_4.set_ylabel(wmean1label[0],fontsize=4.5,rotation=90)
    ax2_4.set_xlim(wmean1lim)
    ax2_4.set_ylim(mudeltalim)
    ax2_4.set_xscale(u'linear')
    ax2_4.set_yscale(u'linear')
    ax2_4.set_xticks(wmean1ticks+[1])
    ax2_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_4.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([wmean1,mudelta])
    density=kde([wmean1,mudelta])
    ax2_4.scatter(wmean1prior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_4.scatter(wmean1,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_4.set_xlim(wmean1lim)
    ax1_4.set_ylim(gammalim)
    ax1_4.set_xscale(u'linear')
    ax1_4.set_yscale(u'linear')
    ax1_4.set_xticks(wmean1ticks+[1])
    ax1_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_4.set_yticks(gammaticks)
    kde=stats.gaussian_kde([wmean1,gamma])
    density=kde([wmean1,gamma])
    ax1_4.scatter(wmean1prior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_4.scatter(wmean1,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_4.set_xticks(wmean1ticks+[1])
    ax0_4.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_4.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_4.hist(wmean1,bins=50,range=wmean1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_4.hist(wmean1prior,bins=50,range=wmean1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_4.hist(wmean1,bins=50,range=wmean1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax7_5.set_xlabel(deltawlabel[0],fontsize=4.5,rotation=0)
#ax7_5.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=90)
    ax7_5.set_xlim(deltawlim)
    ax7_5.set_ylim(vvar1lim)
    ax7_5.set_xscale(u'linear')
    ax7_5.set_yscale(u'linear')
    ax7_5.set_xticks(deltawticks+[3])
    ax7_5.set_xticklabels(deltawticks+[3],rotation=90)
#ax7_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax7_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax7_5.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([deltaw,vvar1])
    density=kde([deltaw,vvar1])
    ax7_5.scatter(deltawprior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax7_5.scatter(deltaw,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax6_5.set_xlabel(deltawlabel[0],fontsize=4.5,rotation=0)
#ax6_5.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=90)
    ax6_5.set_xlim(deltawlim)
    ax6_5.set_ylim(wvar2lim)
    ax6_5.set_xscale(u'linear')
    ax6_5.set_yscale(u'linear')
    ax6_5.set_xticks(deltawticks+[1])
    ax6_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax6_5.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([deltaw,wvar2])
    density=kde([deltaw,wvar2])
    ax6_5.scatter(deltawprior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_5.scatter(deltaw,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax4_5.set_xlabel(deltawlabel[0],fontsize=4.5,rotation=0)
#ax4_5.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=90)
    ax5_5.set_xlim(deltawlim)
    ax5_5.set_ylim(vvar1lim)
    ax5_5.set_xscale(u'linear')
    ax5_5.set_yscale(u'linear')
    ax5_5.set_xticks(deltawticks+[1])
    ax5_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_5.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([deltaw,vvar1])
    density=kde([deltaw,vvar1])
    ax5_5.scatter(deltawprior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_5.scatter(deltaw,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_5.set_xlabel(deltawlabel[0],fontsize=4.5,rotation=0)
#ax3_5.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=90)
    ax4_5.set_xlim(deltawlim)
    ax4_5.set_ylim(vvar2lim)
    ax4_5.set_xscale(u'linear')
    ax4_5.set_yscale(u'linear')
    ax4_5.set_xticks(deltawticks+[1])
    ax4_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_5.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([deltaw,vvar2])
    density=kde([deltaw,vvar2])
    ax4_5.scatter(deltawprior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_5.scatter(deltaw,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_5.set_xlabel(deltawlabel[0],fontsize=4.5,rotation=0)
#ax2_5.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=90)
    ax3_5.set_xlim(deltawlim)
    ax3_5.set_ylim(mualphalim)
    ax3_5.set_xscale(u'linear')
    ax3_5.set_yscale(u'linear')
    ax3_5.set_xticks(deltawticks+[1])
    ax3_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_5.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([deltaw,mualpha])
    density=kde([deltaw,mualpha])
    ax3_5.scatter(deltawprior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_5.scatter(deltaw,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_5.set_xlabel(deltawlabel[0],fontsize=4.5,rotation=0)
#ax1_5.set_ylabel(deltawlabel[0],fontsize=4.5,rotation=90)
    ax2_5.set_xlim(deltawlim)
    ax2_5.set_ylim(mudeltalim)
    ax2_5.set_xscale(u'linear')
    ax2_5.set_yscale(u'linear')
    ax2_5.set_xticks(deltawticks+[1])
    ax2_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_5.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([deltaw,mudelta])
    density=kde([deltaw,mudelta])
    ax2_5.scatter(deltawprior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_5.scatter(deltaw,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_5.set_xlim(deltawlim)
    ax1_5.set_ylim(gammalim)
    ax1_5.set_xscale(u'linear')
    ax1_5.set_yscale(u'linear')
    ax1_5.set_xticks(deltawticks+[1])
    ax1_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_5.set_yticks(gammaticks)
    kde=stats.gaussian_kde([deltaw,gamma])
    density=kde([deltaw,gamma])
    ax1_5.scatter(deltawprior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_5.scatter(deltaw,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_5.set_xticks(deltawticks+[1])
    ax0_5.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_5.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_5.hist(deltaw,bins=50,range=deltawlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_5.hist(deltawprior,bins=50,range=deltawlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_5.hist(deltaw,bins=50,range=deltawlim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax6_6.xaxis.set_label_coords(0.7,-0.4)
    ax6_6.set_xlabel(wvar1label[0],fontsize=4.5,rotation=0)
#ax5_6 set_ylabel(vvar1label[0],fontsize=4.5,rotation=90)
    ax6_6.set_xlim(wvar1lim)
    ax6_6.set_ylim(wvar2lim)
    ax6_6.set_xscale(u'linear')
    ax6_6.set_yscale(u'linear')
    ax6_6.set_xticks(wvar1ticks+[1])
    ax6_6.set_xticklabels(wvar1ticks+[1],rotation=90)
#ax5_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax6_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax6_6.set_yticks(wvar2ticks)
    kde=stats.gaussian_kde([wvar1,wvar2])
    density=kde([wvar1,wvar2])
    ax6_6.scatter(wvar1prior,wvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax6_6.scatter(wvar1,wvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax4_6.set_xlabel(wvar1label[0],fontsize=4.5,rotation=0)
#ax4_6.set_ylabel(wvar1label[0],fontsize=4.5,rotation=90)
    ax5_6.set_xlim(wvar1lim)
    ax5_6.set_ylim(vvar1lim)
    ax5_6.set_xscale(u'linear')
    ax5_6.set_yscale(u'linear')
    ax5_6.set_xticks(wvar1ticks+[1])
    ax5_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_6.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([wvar1,vvar1])
    density=kde([wvar1,vvar1])
    ax5_6.scatter(wvar1prior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_6.scatter(wvar1,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_6.set_xlabel(wvar1label[0],fontsize=4.5,rotation=0)
#ax3_6.set_ylabel(wvar1label[0],fontsize=4.5,rotation=90)
    ax4_6.set_xlim(wvar1lim)
    ax4_6.set_ylim(vvar2lim)
    ax4_6.set_xscale(u'linear')
    ax4_6.set_yscale(u'linear')
    ax4_6.set_xticks(wvar1ticks+[1])
    ax4_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_6.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([wvar1,vvar2])
    density=kde([wvar1,vvar2])
    ax4_6.scatter(wvar1prior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_6.scatter(wvar1,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_6.set_xlabel(wvar1label[0],fontsize=4.5,rotation=0)
#ax2_6.set_ylabel(wvar1label[0],fontsize=4.5,rotation=90)
    ax3_6.set_xlim(wvar1lim)
    ax3_6.set_ylim(mualphalim)
    ax3_6.set_xscale(u'linear')
    ax3_6.set_yscale(u'linear')
    ax3_6.set_xticks(wvar1ticks+[1])
    ax3_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_6.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([wvar1,mualpha])
    density=kde([wvar1,mualpha])
    ax3_6.scatter(wvar1prior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_6.scatter(wvar1,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_6.set_xlabel(wvar1label[0],fontsize=4.5,rotation=0)
#ax1_6.set_ylabel(wvar1label[0],fontsize=4.5,rotation=90)
    ax2_6.set_xlim(wvar1lim)
    ax2_6.set_ylim(mudeltalim)
    ax2_6.set_xscale(u'linear')
    ax2_6.set_yscale(u'linear')
    ax2_6.set_xticks(wvar1ticks+[1])
    ax2_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_6.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([wvar1,mudelta])
    density=kde([wvar1,mudelta])
    ax2_6.scatter(wvar1prior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_6.scatter(wvar1,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_6.set_xlim(wvar1lim)
    ax1_6.set_ylim(gammalim)
    ax1_6.set_xscale(u'linear')
    ax1_6.set_yscale(u'linear')
    ax1_6.set_xticks(wvar1ticks+[1])
    ax1_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_6.set_yticks(gammaticks)
    kde=stats.gaussian_kde([wvar1,gamma])
    density=kde([wvar1,gamma])
    ax1_6.scatter(wvar1prior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_6.scatter(wvar1,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_6.set_xticks(wvar1ticks+[1])
    ax0_6.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_6.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_6.hist(wvar1,bins=50,range=wvar1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_6.hist(wvar1prior,bins=50,range=wvar1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_6.hist(wvar1,bins=50,range=wvar1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax5_7.xaxis.set_label_coords(0.7,-0.4)
    ax5_7.set_xlabel(wvar2label[0],fontsize=4.5,rotation=0)
#ax4_7.set_ylabel(vvar1label[0],fontsize=4.5,rotation=90)
    ax5_7.set_xlim(wvar2lim)
    ax5_7.set_ylim(vvar1lim)
    ax5_7.set_xscale(u'linear')
    ax5_7.set_yscale(u'linear')
    ax5_7.set_xticks(wvar2ticks+[1])
    ax5_7.set_xticklabels(wvar2ticks+[1],rotation=90)
#ax4_7.xaxis.set_major_formatter(plt.NullFormatter())
    ax5_7.yaxis.set_major_formatter(plt.NullFormatter())
    ax5_7.set_yticks(vvar1ticks)
    kde=stats.gaussian_kde([wvar2,vvar1])
    density=kde([wvar2,vvar1])
    ax5_7.scatter(wvar2prior,vvar1prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax5_7.scatter(wvar2,vvar1,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax3_7.set_xlabel(wvar2label[0],fontsize=4.5,rotation=0)
#ax3_7.set_ylabel(wvar2label[0],fontsize=4.5,rotation=90)
    ax4_7.set_xlim(wvar2lim)
    ax4_7.set_ylim(vvar2lim)
    ax4_7.set_xscale(u'linear')
    ax4_7.set_yscale(u'linear')
    ax4_7.set_xticks(wvar2ticks+[1])
    ax4_7.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_7.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_7.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([wvar2,vvar2])
    density=kde([wvar2,vvar2])
    ax4_7.scatter(wvar2prior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_7.scatter(wvar2,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_7.set_xlabel(wvar2label[0],fontsize=4.5,rotation=0)
#ax2_7.set_ylabel(wvar2label[0],fontsize=4.5,rotation=90)
    ax3_7.set_xlim(wvar2lim)
    ax3_7.set_ylim(mualphalim)
    ax3_7.set_xscale(u'linear')
    ax3_7.set_yscale(u'linear')
    ax3_7.set_xticks(wvar2ticks+[1])
    ax3_7.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_7.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_7.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([wvar2,mualpha])
    density=kde([wvar2,mualpha])
    ax3_7.scatter(wvar2prior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_7.scatter(wvar2,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_7.set_xlabel(wvar2label[0],fontsize=4.5,rotation=0)
#ax1_7.set_ylabel(wvar2label[0],fontsize=4.5,rotation=90)
    ax2_7.set_xlim(wvar2lim)
    ax2_7.set_ylim(mudeltalim)
    ax2_7.set_xscale(u'linear')
    ax2_7.set_yscale(u'linear')
    ax2_7.set_xticks(wvar2ticks+[1])
    ax2_7.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_7.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_7.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([wvar2,mudelta])
    density=kde([wvar2,mudelta])
    ax2_7.scatter(wvar2prior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_7.scatter(wvar2,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_7.set_xlim(wvar2lim)
    ax1_7.set_ylim(gammalim)
    ax1_7.set_xscale(u'linear')
    ax1_7.set_yscale(u'linear')
    ax1_7.set_xticks(wvar2ticks+[1])
    ax1_7.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_7.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_7.set_yticks(gammaticks)
    kde=stats.gaussian_kde([wvar2,gamma])
    density=kde([wvar2,gamma])
    ax1_7.scatter(wvar2prior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_7.scatter(wvar2,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_7.set_xticks(wvar2ticks+[1])
    ax0_7.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_7.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_7.hist(wvar2,bins=50,range=wvar2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_7.hist(wvar2prior,bins=50,range=wvar2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_7.hist(wvar2,bins=50,range=wvar2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax4_8.xaxis.set_label_coords(0.6,-0.4)
    ax4_8.set_xlabel(vvar1label[0],fontsize=4.5,rotation=0)
#ax3_8.set_ylabel(vvar2label[0],fontsize=4.5,rotation=90)
    ax4_8.set_xlim(vvar1lim)
    ax4_8.set_ylim(vvar2lim)
    ax4_8.set_xscale(u'linear')
    ax4_8.set_yscale(u'linear')
    ax4_8.set_xticks(vvar1ticks)
    ax4_8.set_xticklabels(vvar1ticks,rotation=90)
#ax3_8.xaxis.set_major_formatter(plt.NullFormatter())
    ax4_8.yaxis.set_major_formatter(plt.NullFormatter())
    ax4_8.set_yticks(vvar2ticks)
    kde=stats.gaussian_kde([vvar1,vvar2])
    density=kde([vvar1,vvar2])
    ax4_8.scatter(vvar1prior,vvar2prior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax4_8.scatter(vvar1,vvar2,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax2_8.set_xlabel(vvar1label[0],fontsize=4.5,rotation=0)
#ax2_8.set_ylabel(vvar1label[0],fontsize=4.5,rotation=90)
    ax3_8.set_xlim(vvar1lim)
    ax3_8.set_ylim(mualphalim)
    ax3_8.set_xscale(u'linear')
    ax3_8.set_yscale(u'linear')
    ax3_8.set_xticks(vvar1ticks+[1])
    ax3_8.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_8.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_8.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([vvar1,mualpha])
    density=kde([vvar1,mualpha])
    ax3_8.scatter(vvar1prior,mualphaprior,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_8.scatter(vvar1,mualpha,1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_8.set_xlabel(vvar1label[0],fontsize=4.5,rotation=0)
#ax1_8.set_ylabel(vvar1label[0],fontsize=4.5,rotation=90)
    ax2_8.set_xlim(vvar1lim)
    ax2_8.set_ylim(mudeltalim)
    ax2_8.set_xscale(u'linear')
    ax2_8.set_yscale(u'linear')
    ax2_8.set_xticks(vvar1ticks+[1])
    ax2_8.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_8.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_8.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([vvar1,mudelta])
    density=kde([vvar1,mudelta])
    ax2_8.scatter(vvar1prior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_8.scatter(vvar1,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax1_8.set_xlim(vvar1lim)
    ax1_8.set_ylim(gammalim)
    ax1_8.set_xscale(u'linear')
    ax1_8.set_yscale(u'linear')
    ax1_8.set_xticks(vvar1ticks+[1])
    ax1_8.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_8.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_8.set_yticks(gammaticks)
    kde=stats.gaussian_kde([vvar1,gamma])
    density=kde([vvar1,gamma])
    ax1_8.scatter(vvar1prior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_8.scatter(vvar1,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_8.set_xticks(vvar1ticks+[1])
    ax0_8.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_8.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_8.hist(vvar1,bins=50,range=vvar1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_8.hist(vvar1prior,bins=50,range=vvar1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_8.hist(vvar1,bins=50,range=vvar1lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax3_9.xaxis.set_label_coords(0.6,-0.4)
    ax3_9.set_xlabel(vvar2label[0],fontsize=4.5,rotation=0)
#ax2_9.set_ylabel(mualphalabel[0],fontsize=4.5,rotation=90)
    ax3_9.set_xlim(vvar2lim)
    ax3_9.set_ylim(mualphalim)
    ax3_9.set_xscale(u'linear')
    ax3_9.set_yscale(u'linear')
    ax3_9.set_xticks(vvar2ticks)
    ax3_9.set_xticklabels(vvar2ticks,rotation=90)
#ax2_9.xaxis.set_major_formatter(plt.NullFormatter())
    ax3_9.yaxis.set_major_formatter(plt.NullFormatter())
    ax3_9.set_yticks(mualphaticks)
    kde=stats.gaussian_kde([vvar2,mualpha])
    density=kde([vvar2,mualpha])
    ax3_9.scatter(vvar2prior,mualphaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax3_9.scatter(vvar2,mualpha,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
#ax1_9.set_xlabel(vvar2label[0],fontsize=4.5,rotation=0)
#ax1_9.set_ylabel(vvar2label[0],fontsize=4.5,rotation=90)
    ax2_9.set_xlim(vvar2lim)
    ax2_9.set_ylim(mudeltalim)
    ax2_9.set_xscale(u'linear')
    ax2_9.set_yscale(u'linear')
    ax2_9.set_xticks(vvar2ticks+[1])
    ax2_9.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_9.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_9.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([vvar2,mudelta])
    density=kde([vvar2,mudelta])
    ax2_9.scatter(vvar2prior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax2_9.scatter(vvar2,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)

    ax1_9.set_xlim(vvar2lim)
    ax1_9.set_ylim(gammalim)
    ax1_9.set_xscale(u'linear')
    ax1_9.set_yscale(u'linear')
    ax1_9.set_xticks(vvar2ticks+[1])
    ax1_9.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_9.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_9.set_yticks(gammaticks)
    kde=stats.gaussian_kde([vvar2,gamma])
    density=kde([vvar2,gamma])
    ax1_9.scatter(vvar2prior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',rasterized=True)
    ax1_9.scatter(vvar2,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',rasterized=True)
    
    ax0_9.set_xticks(vvar2ticks+[1])
    ax0_9.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_9.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_9.hist(vvar2,bins=50,range=vvar2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_9.hist(vvar2prior,bins=50,range=vvar2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25)
    ax0_9.hist(vvar2,bins=50,range=vvar2lim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    
    
    ax2_10.xaxis.set_label_coords(0.6,-0.55)
    ax2_10.set_xlabel(mualphalabel[0],fontsize=4.5,rotation=0)
#ax1_10.set_ylabel(mudeltalabel[0],fontsize=4.5,rotation=90)
    ax2_10.set_xlim(mualphalim)
    ax2_10.set_ylim(mudeltalim)
    ax2_10.set_xscale(u'linear')
    ax2_10.set_yscale(u'linear')
    ax2_10.set_xticks(mualphaticks)
    ax2_10.set_xticklabels(mualphaticks,rotation=90)
#ax1_10.xaxis.set_major_formatter(plt.NullFormatter())
    ax2_10.yaxis.set_major_formatter(plt.NullFormatter())
    ax2_10.set_yticks(mudeltaticks)
    kde=stats.gaussian_kde([mualpha,mudelta])
    density=kde([mualpha,mudelta])
    kde=stats.gaussian_kde([mualpha,mudelta])
    density=kde([mualpha,mudelta])
    ax2_10.scatter(mualphaprior,mudeltaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',label="Prior",rasterized=True)
    ax2_10.scatter(mualpha,mudelta,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',label="Posterior",rasterized=True)

    ax1_10.set_xlim(mualphalim)
    ax1_10.set_ylim(gammalim)
    ax1_10.set_xscale(u'linear')
    ax1_10.set_yscale(u'linear')
    ax1_10.set_xticks(mualphaticks)
    ax1_10.set_xticklabels(mualphaticks,rotation=90)
    ax1_10.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_10.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_10.set_yticks(gammaticks)
    kde=stats.gaussian_kde([mualpha,gamma])
    density=kde([mualpha,gamma])
    kde=stats.gaussian_kde([mualpha,gamma])
    density=kde([mualpha,gamma])
    ax1_10.scatter(mualphaprior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',label="Prior",rasterized=True)
    ax1_10.scatter(mualpha,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',label="Posterior",rasterized=True)
    
    ax0_10.set_xticks(mualphaticks)
    ax0_10.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_10.yaxis.set_major_formatter(plt.NullFormatter())
    ax0_10.hist(mualpha,bins=50,range=mualphalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_10.hist(mualphaprior,bins=50,range=mualphalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25,label="Prior")
    ax0_10.hist(mualpha,bins=50,range=mualphalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25,label="Posterior")
    
    
    ax1_11.xaxis.set_label_coords(0.6,-0.55)
    ax1_11.set_xlabel(mudeltalabel[0],fontsize=4.5,rotation=0)
#ax1_10.set_ylabel(gammalabel[0],fontsize=4.5,rotation=90)
    ax1_11.set_xlim(mudeltalim)
    ax1_11.set_ylim(gammalim)
    ax1_11.set_xscale(u'linear')
    ax1_11.set_yscale(u'linear')
    ax1_11.set_xticks(mudeltaticks)
    ax1_11.set_xticklabels(mudeltaticks,rotation=90)
#ax1_10.xaxis.set_major_formatter(plt.NullFormatter())
    ax1_11.yaxis.set_major_formatter(plt.NullFormatter())
    ax1_11.set_yticks(gammaticks)
    kde=stats.gaussian_kde([mudelta,gamma])
    density=kde([mudelta,gamma])
    kde=stats.gaussian_kde([mudelta,gamma])
    density=kde([mudelta,gamma])
    ax1_11.scatter(mudeltaprior,gammaprior,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='k',label="Prior",rasterized=True)
    ax1_11.scatter(mudelta,gamma,s=1,lw=0,edgecolor='none',alpha=0.3,marker='.',color='r',label="Posterior",rasterized=True)
    
    ax0_11.set_yticks(mudeltaticks)
    ax0_11.xaxis.set_major_formatter(plt.NullFormatter())
    ax0_11.yaxis.set_major_formatter(plt.NullFormatter())
#    ax0_11.set_xlabel(mudeltalabel[0],fontsize=4.5,rotation=90)
    ax0_11.hist(mudelta,bins=50,range=mudeltalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25)
    ax0_11.hist(mudeltaprior,bins=50,range=mudeltalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='k',linewidth=0.25,label="Prior")
    ax0_11.hist(mudelta,bins=50,range=mudeltalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='vertical',color='r',linewidth=0.25,label="Posterior")


    if i != 0:
        ax1_12.xaxis.set_label_coords(0.5,-0.1)
        ax1_12.set_yticks(gammaticks)
        ax1_12.xaxis.set_major_formatter(plt.NullFormatter())
        ax1_12.yaxis.set_major_formatter(plt.NullFormatter())
        ax1_12.set_xlabel('probability',fontsize=4.5,rotation=0)
    #    ax1_12.set_ylabel(gammalabel,fontsize=4.5,rotation=90)
        ax1_12.hist(gamma,bins=50,range=gammalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='horizontal',color='r',linewidth=0.25)
        ax1_12.hist(gammaprior,bins=50,range=gammalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='horizontal',color='k',linewidth=0.25,label="Prior")
        ax1_12.hist(gamma,bins=50,range=gammalim,normed=True,histtype='step',align='mid',rwidth=0,orientation='horizontal',color='r',linewidth=0.25,label="Posterior")
        ax1_12.legend(loc=2,fontsize=4.5,shadow='False',handlelength=1,bbox_to_anchor=[0.01,1.9])
    
    plotfilename=dsph[i]+'_wp11_params.pdf'
    plt.savefig(plotfilename,dpi=400)
#plt.show()
    plt.close()
    
    
    
    
